////////////////////////////////////////////////////////////////// Cancel Fireball If Enemy Has Moved Closer
// If casting a fireball and target is within 17ft cancel it
IF
	GlobalTimerNotExpired("castingfireball","LOCALS")
	Range(LastSeenBy(Myself),17)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71459) // Cancelling Fireball
		SetGlobalTimer("castingfireball","LOCALS",0)
		ClearAllActions()
END

// If casting fireball and target still far away, continue until cast and don't continue with other actions
IF
	GlobalTimerNotExpired("castingfireball","LOCALS")
THEN
	RESPONSE #100
		// Continue with current action
END

////////////////////////////////////////////////////////////////// Status Messages

IF
	!GlobalTimerNotExpired("energyleveldrained","LOCALS")
	CheckStatGT(Myself,0,LEVELDRAIN)
THEN
	RESPONSE #100
		SetGlobalTimer("energyleveldrained","LOCALS",3)
		DisplayStringHead(Myself,71451) // Status: Energy Level Drained
		Continue()
END

////////////////////////////////////////////////////////////////// If poisoned use an antidote potion
IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	StateCheck(Myself,STATE_POISONED) 
	HasItem("potn20",Myself)  // Antidote
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71380) // Potion: Antidote
		UseItem("potn20",Myself)  // Antidote
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	StateCheck(Myself,STATE_POISONED)
	HasItem("potn17",Myself)  // Elixir of health - cures disease and poisons
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71381) // Potion: Elixir Of Health
		UseItem("potn17",Myself)  // Elixir of health - cures disease and poisons
END

////////////////////////////////////////////////////////////////// Share Antidotes

IF
	ActionListEmpty()
    StateCheck(Myself,STATE_POISONED)
	!HasItem("potn17",Myself)
    !HasItem("potn20",Myself)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71462) // Help: Need Antidote
        Shout(NEED_ANTIDOTE) // Shout for help
END

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_ANTIDOTE) // If someone shouted for help
    !HasItem("potn20",LastHeardBy(Myself))
	HasItem("potn20",Myself)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71463) // Giving Antidote
        GiveItem("potn20",LastHeardBy(Myself))
END

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_ANTIDOTE) // If someone shouted for help
    !HasItem("potn17",LastHeardBy(Myself))
	HasItem("potn17",Myself)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71463) // Giving Antidote
        GiveItem("potn17",LastHeardBy(Myself))
END

////////////////////////////////////////////////////////////////////////////////////// Buff Potions

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	OR(2)
		HitBy([ENEMY],FIRE)
		HitBy([ENEMY],MAGICFIRE)
	DamageTakenGT(25)
	HasItem("potn02",Myself)
	CheckStatLT(Myself,49,RESISTFIRE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71447) // Potion: Fire Resistance
		UseItem("potn02",Myself)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	OR(2)
		HitBy([ENEMY],COLD)
		HitBy([ENEMY],MAGICCOLD)
	DamageTakenGT(25)
	HasItem("potn22",Myself)
	CheckStatLT(Myself,49,RESISTCOLD)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71448) // Potion: Cold Resistance
		UseItem("potn22",Myself)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HitBy([ENEMY],ELECTRICITY)
	DamageTakenGT(25)
	HasItem("potn31",Myself)
	CheckStatLT(Myself,49,RESISTELECTRICITY)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71449) // Potion: Insulation
		UseItem("potn31",Myself)
END

//////////////////////////////////////////////////////////////////// If ally health is low and have heal spell, heal them
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),80)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71375) // Spell: Cure Light Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_LIGHT_WOUNDS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),80) 

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71376) // Spell: Cure Medium Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),75)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71377) // Spell: Cure Serious Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
	HPPercentLT(MostDamagedOf(Myself),65)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
		SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71461) // Spell: Mass Cure
		Spell(MostDamagedOf(Myself),CLERIC_MASS_CURE)
END

/////////////////////////////////////////////////////////////////// If health is low use a healing potion

// check hp < maxhp - 27
// per = hp/maxhp*100
// hp > 27*per/(100-per)
// if per < x and hp > 27*x/(100-x)

// Potion 52 - Potion Of Extra Healing

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,10) 
	HPGT(Myself,3)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,20) 
	HPGT(Myself,7)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,30) 
	HPGT(Myself,12)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,40) 
	HPGT(Myself,18)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,50) 
	HPGT(Myself,27)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,60) 
	HPGT(Myself,41)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

// check hp <= maxhp - 9
// per = hp/maxhp*100
// hp >= 9*per/(100-per)
// if per < x and hp > 9*x/(100-x)

// Potion 8 - Potion Of Healing

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,10) 
	HPGT(Myself,1)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,20) 
	HPGT(Myself,2)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,30) 
	HPGT(Myself,4)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,40) 
	HPGT(Myself,6)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,50) 
	HPGT(Myself,9)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,60) 
	HPGT(Myself,14)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,70) 
	HPGT(Myself,21)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

// Potion 25 - Potion Of Healing

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,10) 
	HPGT(Myself,1)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,20) 
	HPGT(Myself,2)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,30) 
	HPGT(Myself,4)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,40) 
	HPGT(Myself,6)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,50) 
	HPGT(Myself,9)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,60) 
	HPGT(Myself,14)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,70) 
	HPGT(Myself,21)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

////////////////////////////////////////////////////////////////// Share Healing Potions

IF
	ActionListEmpty()
    !HasItem("potn08",Myself)
    HPPercentLT(Myself,50)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71457) // Help: Need Potion Of Healing
        Shout(NEED_POTION_OF_HEALING) // Shout for help
END

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_POTION_OF_HEALING) // If someone shouted for help
    !HasItem("potn08",LastHeardBy(Myself))
	HasItem("potn08",Myself)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71458) // Giving Healing Potion
        GiveItem("potn08",LastHeardBy(Myself)) // Pass them the item
END

////////////////////////////////////////////////////////////////// if diseased use cure disease potion
IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	OR(2)
		StateCheck(Myself,STATE_DISEASED) 
		HPPercentLT(Myself,60) // If health is low use a potion
	HasItem("potn17",Myself)  // Elixir of health - cures disease and poisons
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71381) // Potion: Elixir Of Health
		UseItem("potn17",Myself)  // Elixir of health - cures disease and poisons
END

//////////////////////////////////////////////////////////////// Run away from nearby enemies if health is low
// If an enemy is nearby and the same location timer isn't running, then start the timer and run away
IF 
	ActionListEmpty()
	HPPercentLT(Myself,60)
	!GlobalTimerExpired("locMeSame","LOCALS")
	!GlobalTimerNotExpired("locMeSame","LOCALS")
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71382) // Running Away
		SetGlobalTimer("locMeSame","LOCALS",3)
		RunAwayFrom(NearestEnemyOf(Myself),20)
END

IF 
	ActionListEmpty()
	HPPercentLT(Myself,60)
	!GlobalTimerExpired("locMeSame","LOCALS")
	!GlobalTimerNotExpired("locMeSame","LOCALS")
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71382) // Running Away
		SetGlobalTimer("locMeSame","LOCALS",3)
		RunAwayFrom(NearestEnemyOf(Myself),25)
END

// If an enemy is nearby and the same location timer is running but hasn't expired, then run away
IF 
	ActionListEmpty()
	HPPercentLT(Myself,60)
	GlobalTimerNotExpired("locMeSame","LOCALS")
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71382) // Running Away
		RunAwayFrom(NearestEnemyOf(Myself),15)
END

// If an enemy is nearby and the same location timer has expired (have been in the same spot for a while), continue with normal actions and attack

////////////////////////////////////////////////////////////////////////////////////// Debuff/Control Spells
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	OR(9)
		SpellCast([ANYONE],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([ANYONE],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([ANYONE],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([ANYONE],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([ANYONE],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([ANYONE],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([ANYONE],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([ANYONE],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([ANYONE],CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
		SpellCast([ANYONE],TRAP_STINKING_CLOUD)
		SpellCast([ANYONE],TRAP_CLOUDKILL)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
		SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71442) // Spell: Zone Of Sweet Air
		Spell(Myself,CLERIC_ZONE_OF_SWEET_AIR)
END

// Level 2 - Alteration
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Silence, 15' Radius)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71383) // Spell: Silence
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Silence, 15' Radius)
END

// Level 4 - Abjuration
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SECRET_WORD)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!ImmuneToSpellLevel(LastSeenBy(Myself),4)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71384) // Spell: Secret Word
		Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)
END

// Level 2 - Divination
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)
	OR(2)
		SpellCast([EVILCUTOFF],WIZARD_INVISIBILITY)
		SpellCast([EVILCUTOFF],WIZARD_IMPROVED_INVISIBILITY)
	!ImmuneToSpellLevel(LastTrigger,2)
	!CheckStat(LastTrigger,1,MINORGLOBE)
	!CheckStat(LastTrigger,1,WIZARD_SPELL_TURNING)
	!CheckStat(LastTrigger,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(LastTrigger,3,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71450) // Spell: Detect Invisibility
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)
END

// Level 2 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)
	See([EVILCUTOFF.HUMANOID])
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71460) // Spell: Hold Person
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

// Level 3 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HOLD_PERSON)
	See([EVILCUTOFF.HUMANOID])
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71460) // Spell: Hold Person
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

// Level 5 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HOLD_MONSTER)
	See(NearestEnemyOf(Myself))
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),5)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71385) // Spell: Hold Monster
		Spell(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)
END

// Level 5 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_CHAOS)  // SPPR211.SPL (Silence, 15' Radius)
	NumCreatureVsPartyGT(Myself,3)

	!StateCheck(NearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(NearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),5)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)	
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),5)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	CheckStatGT(SecondNearestEnemyOf(Myself),5,SAVEVSSPELL)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),5)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	CheckStatGT(ThirdNearestEnemyOf(Myself),5,SAVEVSSPELL)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),5)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	CheckStatGT(FourthNearestEnemyOf(Myself),5,SAVEVSSPELL)

	See(NearestEnemyOf(Myself))

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71386) // Spell: Chaos
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)
END

// Level 2 - Necromancy
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HORROR)
	NumCreatureVsPartyGT(Myself,4)

	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),2)
	!CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	!Race(NearestEnemyOf(Myself),DEMONIC)
	!Kit(NearestEnemyOf(Myself),CAVALIER)
	!Kit(NearestEnemyOf(Myself),Blackguard)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),2)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(SecondNearestEnemyOf(Myself),UNDEAD)
	!Race(SecondNearestEnemyOf(Myself),DEMONIC)
	!Kit(SecondNearestEnemyOf(Myself),CAVALIER)
	!Kit(SecondNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(SecondNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),2)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(ThirdNearestEnemyOf(Myself),UNDEAD)
	!Race(ThirdNearestEnemyOf(Myself),DEMONIC)
	!Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
	!Kit(ThirdNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(ThirdNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),2)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FourthNearestEnemyOf(Myself),UNDEAD)
	!Race(FourthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FourthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FourthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FourthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FifthNearestEnemyOf(Myself),2)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FifthNearestEnemyOf(Myself),UNDEAD)
	!Race(FifthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FifthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FifthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FifthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71387) // Spell: Horror
		Spell(NearestEnemyOf(Myself),WIZARD_HORROR)
END


// Dispel Magic On Enemies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_BREACH)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),5)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71452) // Spell: Breach
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

// Wizard True Dispel Magic = Dispel Magic
// Dispel Magic On Allies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot1,HOPELESSNESS)
		CheckSpellState(PartySlot1,ENFEEBLED)
		CheckSpellState(PartySlot1,HELD)
		CheckSpellState(PartySlot1,ENTANGLE)
		CheckSpellState(PartySlot1,WEB)
		CheckSpellState(PartySlot1,DOOM)
		StateCheck(PartySlot1,STATE_PANIC)
		StateCheck(PartySlot1,STATE_CHARMED)
		StateCheck(PartySlot1,STATE_CONFUSED)
		StateCheck(PartySlot1,STATE_SLEEPING)
		StateCheck(PartySlot1,STATE_SLOWED)
	See(PartySlot1)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot2,HOPELESSNESS)
		CheckSpellState(PartySlot2,ENFEEBLED)
		CheckSpellState(PartySlot2,HELD)
		CheckSpellState(PartySlot2,ENTANGLE)
		CheckSpellState(PartySlot2,WEB)
		CheckSpellState(PartySlot2,DOOM)
		StateCheck(PartySlot2,STATE_PANIC)
		StateCheck(PartySlot2,STATE_CHARMED)
		StateCheck(PartySlot2,STATE_CONFUSED)
		StateCheck(PartySlot2,STATE_SLEEPING)
		StateCheck(PartySlot2,STATE_SLOWED)
	See(PartySlot2)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot3,HOPELESSNESS)
		CheckSpellState(PartySlot3,ENFEEBLED)
		CheckSpellState(PartySlot3,HELD)
		CheckSpellState(PartySlot3,ENTANGLE)
		CheckSpellState(PartySlot3,WEB)
		CheckSpellState(PartySlot3,DOOM)
		StateCheck(PartySlot3,STATE_PANIC)
		StateCheck(PartySlot3,STATE_CHARMED)
		StateCheck(PartySlot3,STATE_CONFUSED)
		StateCheck(PartySlot3,STATE_SLEEPING)
		StateCheck(PartySlot3,STATE_SLOWED)
	See(PartySlot3)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot4,HOPELESSNESS)
		CheckSpellState(PartySlot4,ENFEEBLED)
		CheckSpellState(PartySlot4,HELD)
		CheckSpellState(PartySlot4,ENTANGLE)
		CheckSpellState(PartySlot4,WEB)
		CheckSpellState(PartySlot4,DOOM)
		StateCheck(PartySlot4,STATE_PANIC)
		StateCheck(PartySlot4,STATE_CHARMED)
		StateCheck(PartySlot4,STATE_CONFUSED)
		StateCheck(PartySlot4,STATE_SLEEPING)
		StateCheck(PartySlot4,STATE_SLOWED)
	See(PartySlot4)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot5,HOPELESSNESS)
		CheckSpellState(PartySlot5,ENFEEBLED)
		CheckSpellState(PartySlot5,HELD)
		CheckSpellState(PartySlot5,ENTANGLE)
		CheckSpellState(PartySlot5,WEB)
		CheckSpellState(PartySlot5,DOOM)
		StateCheck(PartySlot5,STATE_PANIC)
		StateCheck(PartySlot5,STATE_CHARMED)
		StateCheck(PartySlot5,STATE_CONFUSED)
		StateCheck(PartySlot5,STATE_SLEEPING)
		StateCheck(PartySlot5,STATE_SLOWED)
	See(PartySlot5)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot6,HOPELESSNESS)
		CheckSpellState(PartySlot6,ENFEEBLED)
		CheckSpellState(PartySlot6,HELD)
		CheckSpellState(PartySlot6,ENTANGLE)
		CheckSpellState(PartySlot6,WEB)
		CheckSpellState(PartySlot6,DOOM)
		StateCheck(PartySlot6,STATE_PANIC)
		StateCheck(PartySlot6,STATE_CHARMED)
		StateCheck(PartySlot6,STATE_CONFUSED)
		StateCheck(PartySlot6,STATE_SLEEPING)
		StateCheck(PartySlot6,STATE_SLOWED)
	See(PartySlot6)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

// Dispel Magic On Enemies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

// Wizard Dispel Magic = Remove Magic
// Level 3 - Abjuration
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71388) // Spell: Remove Magic
		Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

// Cleric Dispel Magic = Dispel Magic
// Level 3 - Abjuration
// Dispel Magic On Allies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot1,HOPELESSNESS)
		CheckSpellState(PartySlot1,ENFEEBLED)
		CheckSpellState(PartySlot1,HELD)
		CheckSpellState(PartySlot1,ENTANGLE)
		CheckSpellState(PartySlot1,WEB)
		CheckSpellState(PartySlot1,DOOM)
		StateCheck(PartySlot1,STATE_PANIC)
		StateCheck(PartySlot1,STATE_CHARMED)
		StateCheck(PartySlot1,STATE_CONFUSED)
		StateCheck(PartySlot1,STATE_SLEEPING)
		StateCheck(PartySlot1,STATE_SLOWED)
	See(PartySlot1)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot2,HOPELESSNESS)
		CheckSpellState(PartySlot2,ENFEEBLED)
		CheckSpellState(PartySlot2,HELD)
		CheckSpellState(PartySlot2,ENTANGLE)
		CheckSpellState(PartySlot2,WEB)
		CheckSpellState(PartySlot2,DOOM)
		StateCheck(PartySlot2,STATE_PANIC)
		StateCheck(PartySlot2,STATE_CHARMED)
		StateCheck(PartySlot2,STATE_CONFUSED)
		StateCheck(PartySlot2,STATE_SLEEPING)
		StateCheck(PartySlot2,STATE_SLOWED)
	See(PartySlot2)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot3,HOPELESSNESS)
		CheckSpellState(PartySlot3,ENFEEBLED)
		CheckSpellState(PartySlot3,HELD)
		CheckSpellState(PartySlot3,ENTANGLE)
		CheckSpellState(PartySlot3,WEB)
		CheckSpellState(PartySlot3,DOOM)
		StateCheck(PartySlot3,STATE_PANIC)
		StateCheck(PartySlot3,STATE_CHARMED)
		StateCheck(PartySlot3,STATE_CONFUSED)
		StateCheck(PartySlot3,STATE_SLEEPING)
		StateCheck(PartySlot3,STATE_SLOWED)
	See(PartySlot3)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot4,HOPELESSNESS)
		CheckSpellState(PartySlot4,ENFEEBLED)
		CheckSpellState(PartySlot4,HELD)
		CheckSpellState(PartySlot4,ENTANGLE)
		CheckSpellState(PartySlot4,WEB)
		CheckSpellState(PartySlot4,DOOM)
		StateCheck(PartySlot4,STATE_PANIC)
		StateCheck(PartySlot4,STATE_CHARMED)
		StateCheck(PartySlot4,STATE_CONFUSED)
		StateCheck(PartySlot4,STATE_SLEEPING)
		StateCheck(PartySlot4,STATE_SLOWED)
	See(PartySlot4)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot5,HOPELESSNESS)
		CheckSpellState(PartySlot5,ENFEEBLED)
		CheckSpellState(PartySlot5,HELD)
		CheckSpellState(PartySlot5,ENTANGLE)
		CheckSpellState(PartySlot5,WEB)
		CheckSpellState(PartySlot5,DOOM)
		StateCheck(PartySlot5,STATE_PANIC)
		StateCheck(PartySlot5,STATE_CHARMED)
		StateCheck(PartySlot5,STATE_CONFUSED)
		StateCheck(PartySlot5,STATE_SLEEPING)
		StateCheck(PartySlot5,STATE_SLOWED)
	See(PartySlot5)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot6,HOPELESSNESS)
		CheckSpellState(PartySlot6,ENFEEBLED)
		CheckSpellState(PartySlot6,HELD)
		CheckSpellState(PartySlot6,ENTANGLE)
		CheckSpellState(PartySlot6,WEB)
		CheckSpellState(PartySlot6,DOOM)
		StateCheck(PartySlot6,STATE_PANIC)
		StateCheck(PartySlot6,STATE_CHARMED)
		StateCheck(PartySlot6,STATE_CONFUSED)
		StateCheck(PartySlot6,STATE_SLEEPING)
		StateCheck(PartySlot6,STATE_SLOWED)
	See(PartySlot6)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

// Dispel Magic On Enemies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

// Level 3 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_MISCAST_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	!CheckSpellState(LastSeenBy(Myself),MISCAST_MAGIC)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71390) // Spell: Miscast Magic
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END

IF
 	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DOOM)
	See(NearestEnemyOf(Myself))
	OR(4)
		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
		CheckStatLT(LastSeenBy(Myself),10,THAC0)
	!CheckSpellState(LastSeenBy(Myself),DOOM)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71439) // Spell: Doom
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)
	See(NearestEnemyOf(Myself))
	!CheckSpellState(NearestEnemyOf(Myself),MALISON)
	OR(4)
		CheckStatLT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
		CheckStatLT(NearestEnemyOf(Myself),0,ARMORCLASS)
		CheckStatGT(NearestEnemyOf(Myself),75,MAXHITPOINTS)
		CheckStatLT(NearestEnemyOf(Myself),10,THAC0)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71440) // Spell: Greater Malison
		Spell(NearestEnemyOf(Myself),WIZARD_GREATER_MALISON)
END

/////////////////////////////////////////////////////////////////////////////////////// Debuff/Control Wands
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HasItem("wand02",Myself)
	NumCreatureVsPartyGT(Myself,4)

	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),2)
	!CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	!Race(NearestEnemyOf(Myself),DEMONIC)
	!Kit(NearestEnemyOf(Myself),CAVALIER)
	!Kit(NearestEnemyOf(Myself),Blackguard)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),2)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(SecondNearestEnemyOf(Myself),UNDEAD)
	!Race(SecondNearestEnemyOf(Myself),DEMONIC)
	!Kit(SecondNearestEnemyOf(Myself),CAVALIER)
	!Kit(SecondNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(SecondNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),2)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(ThirdNearestEnemyOf(Myself),UNDEAD)
	!Race(ThirdNearestEnemyOf(Myself),DEMONIC)
	!Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
	!Kit(ThirdNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(ThirdNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),2)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FourthNearestEnemyOf(Myself),UNDEAD)
	!Race(FourthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FourthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FourthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FourthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FifthNearestEnemyOf(Myself),2)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FifthNearestEnemyOf(Myself),UNDEAD)
	!Race(FifthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FifthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FifthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FifthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71430) // Wand: Fear
		UseItem("wand02",NearestEnemyOf(Myself))
END

IF
  	ActionListEmpty()
	Class(Myself,MAGE_ALL)
	HasItem("wand08",Myself)
	NumCreatureVsPartyGT(Myself,4)

	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),1)
	!CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	!Race(NearestEnemyOf(Myself),DEMONIC)
	!Race(NearestEnemyOf(Myself),ELF)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(NearestEnemyOf(Myself),5)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),1)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(SecondNearestEnemyOf(Myself),UNDEAD)
	!Race(SecondNearestEnemyOf(Myself),DEMONIC)
	!Race(SecondNearestEnemyOf(Myself),ELF)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(SecondNearestEnemyOf(Myself),5)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),1)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(ThirdNearestEnemyOf(Myself),UNDEAD)
	!Race(ThirdNearestEnemyOf(Myself),DEMONIC)
	!Race(ThirdNearestEnemyOf(Myself),ELF)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(ThirdNearestEnemyOf(Myself),5)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),1)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FourthNearestEnemyOf(Myself),UNDEAD)
	!Race(FourthNearestEnemyOf(Myself),DEMONIC)
	!Race(FourthNearestEnemyOf(Myself),ELF)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(FourthNearestEnemyOf(Myself),5)

	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FifthNearestEnemyOf(Myself),1)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FifthNearestEnemyOf(Myself),UNDEAD)
	!Race(FifthNearestEnemyOf(Myself),DEMONIC)
	!Race(FifthNearestEnemyOf(Myself),ELF)
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(FifthNearestEnemyOf(Myself),5)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)

	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSWANDS)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71435) // Wand: Sleep
		UseItem("wand08",NearestEnemyOf(Myself))
END

IF
  	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HasItem("wand04",Myself)
	!CheckSpellState(NearestEnemyOf(Myself),HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED | STATE_HELPLESS)
	CheckStatGT(NearestEnemyOf(Myself),10,SAVEVSWANDS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	OR(4)
		CheckStatLT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
		CheckStatLT(NearestEnemyOf(Myself),0,ARMORCLASS)
		CheckStatGT(NearestEnemyOf(Myself),75,MAXHITPOINTS)
		CheckStatLT(NearestEnemyOf(Myself),10,THAC0)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71432) // Wand: Paralyzation
		UseItem("wand04",NearestEnemyOf(Myself))
END

/////////////////////////////////////////////////////////////////////////////////////// Turn Undead
// Start turning undead if can turn nearby undead
IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(Nearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(Nearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(SecondNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(SecondNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(ThirdNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(ThirdNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(FourthNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(FourthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(FifthNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(FifthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(SixthNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(SixthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(SeventhNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(SeventhNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

// Keep turning undead if already turning nearby undead
IF
	ActionListEmpty()
	ModalState(TURNUNDEAD)
	Range([EVILCUTOFF.UNDEAD],12)
	OR(7)
		CanTurn(Nearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SecondNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(ThirdNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(FourthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(FifthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SixthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SeventhNearest([EVILCUTOFF.UNDEAD]),5)
THEN
	RESPONSE #100
END

/////////////////////////////////////////////////////////////////////////////////////// Summon spells
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMATE_DEAD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71392) // Spell: Animate Undead
		Spell(Myself,CLERIC_ANIMATE_DEAD)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_ANIMATE_DEAD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71392) // Spell: Animate Undead
		Spell(Myself,WIZARD_ANIMATE_DEAD)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CALL_WOODLAND_BEINGS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71393) // Spell: Call Woodland Beings
		Spell(Myself,CLERIC_CALL_WOODLAND_BEINGS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMAL_SUMMONING_3)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71394) // Spell: Animal Summoning 3
		Spell(Myself,CLERIC_ANIMAL_SUMMONING_3)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMAL_SUMMONING_2)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71395) // Spell: Animal Summoning 2
		Spell(Myself,CLERIC_ANIMAL_SUMMONING_2)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMAL_SUMMONING_1)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71396) // Spell: Animal Summoning 1
		Spell(Myself,CLERIC_ANIMAL_SUMMONING_1)
END

////////////////////////////////////////////////////////////////////////////////// If have a buff spell use it
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BLESS)  // SPPR101.SPL (Bless)
	!StateCheck(Myself,STATE_BLESS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71397) // Spell: Bless
		Spell(Myself,CLERIC_BLESS)  // SPPR101.SPL (Bless)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Chant)
	!StateCheck(Myself,STATE_CHANT)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71398) // Spell: Chant
		Spell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DEFENSIVE_HARMONY)  // SPPR203.SPL (Chant)
	!CheckStat(Myself,1,CLERIC_DEFENSIVE_HARMONY)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71399) // Spell: Defensive Harmony
		Spell(Myself,CLERIC_DEFENSIVE_HARMONY)  // SPPR203.SPL (Chant)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR203.SPL (Chant)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71400) // Spell: Remove Fear
		Spell(Myself,CLERIC_REMOVE_FEAR)  // SPPR203.SPL (Chant)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot2,PROTECTION_FROM_EVIL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot2,CLERIC_PROTECT_FROM_EVIL)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
	!CheckSpellState(Myself,PROTECTION_FROM_EVIL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71402) // Spell: Protection Group From Evil
		Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot2,BARKSKIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71403) // Spell: Barkskin
		Spell(PartySlot2,CLERIC_BARKSKIN)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_AID)
	!CheckSpellState(PartySlot2,AID)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71404) // Spell: Aid
		Spell(PartySlot2,CLERIC_AID)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_CHAOS_SHIELD)
	!CheckSpellState(Myself,CHAOS_SHIELD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71405) // Spell: Chaos Shield
		Spell(Myself,WIZARD_CHAOS_SHIELD)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SHIELD)
	!CheckSpellState(Myself,WIZARD_SHIELD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71406) // Spell: Shield
		Spell(Myself,WIZARD_SHIELD)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_SHILLELAGH)  // SPPR110.SPL (Shillelagh)
	!HasItem("FBLADE",Myself)  // Flame Blade
	!HasItem("SHILLE",Myself)  // Shillelagh
	!HasItem("SHAMMR",Myself)  // Spiritual Hammer
	!HasItem("CHILLT",Myself)  // Chill Touch
	!HasItem("GHOULT",Myself)  // Ghoul Touch
	!HasItem("SGRASP",Myself)  // Shocking Grasp

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71407) // Spell: Shillelagh
		Spell(Myself,CLERIC_SHILLELAGH)  // SPPR110.SPL (Shillelagh)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FLAME_BLADE)
	!HasItem("FBLADE",Myself)  // Flame Blade
	!HasItem("SHILLE",Myself)  // Shillelagh
	!HasItem("SHAMMR",Myself)  // Spiritual Hammer
	!HasItem("CHILLT",Myself)  // Chill Touch
	!HasItem("GHOULT",Myself)  // Ghoul Touch
	!HasItem("SGRASP",Myself)  // Shocking Grasp

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71408) // Spell: Flame Blade
		Spell(Myself,CLERIC_FLAME_BLADE)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
	!CheckSpellState(Myself,DRAW_UPON_HOLY_MIGHT)
	!StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71409) // Spell: Holy Might
		Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WHITE_HOLY_MIGHT)
	!CheckSpellState(Myself,DRAW_UPON_HOLY_MIGHT)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71409) // Spell: Holy Might
		Spell(Myself,WHITE_HOLY_MIGHT)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH)
	!CheckSpellState(Myself,ARMOR_OF_FAITH)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71410) // Spell: Armor Of Faith
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLY_POWER)
	!CheckSpellState(Myself,HOLY_POWER)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71411) // Spell: Holy Power
		Spell(Myself,CLERIC_HOLY_POWER)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_RESIST_FEAR)
	!CheckSpellState(Myself,RESIST_FEAR)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71412) // Spell: Resist Fear
		Spell(Myself,WIZARD_RESIST_FEAR)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HASTE)
	!StateCheck(Myself,STATE_HASTED)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71413) // Spell: Haste
		Spell(Myself,WIZARD_HASTE)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MIRROR_IMAGE)
	!StateCheck(Myself,STATE_MIRRORIMAGE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71414) // Spell: Mirror Image
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
	!CheckStat(Myself,1,MINORGLOBE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71415) // Spell: Minor Globe Of Invulnerability
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
	!CheckStat(Myself,1,WIZARD_SPELL_DEFLECTION)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71416) // Spell: Minor Spell Deflection
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71417) // Spell: Improved Invisibility
		Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

// Level 3 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)
	!HasItem("MELFMET",Myself)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71445) // Spell: Melfs Minute Meteors
		Spell(Myself,WIZARD_MELF_METEOR)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_IRONSKIN)
	!CheckSpellState(Myself,IRON_SKINS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71453) // Spell: Iron Skins
		Spell(Myself,CLERIC_IRONSKIN)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_STRENGTH_OF_ONE)
	CheckStatLT(WeakestOf(Myself),18,STRENGTH_MODIFIER)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71454) // Spell: Strength Of One
		Spell(WeakestOf(Myself),CLERIC_STRENGTH_OF_ONE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_STRENGTH)
	CheckStatLT(WeakestOf(Myself),18,STRENGTH_MODIFIER)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71455) // Spell: Strength
		Spell(WeakestOf(Myself),WIZARD_STRENGTH)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAMPIONS_STRENGTH)
	CheckStatLT(WeakestOf(Myself),18,STRENGTH_MODIFIER)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71456) // Spell: Champions Strength
		Spell(WeakestOf(Myself),CLERIC_CHAMPIONS_STRENGTH)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71464) // Spell: Righteous Magic
		Spell(WeakestOf(Myself),CLERIC_RIGHTEOUS_MAGIC)
END

//////////////////////////////////////////////////////////////////////////// Decide On Next Target You Can See
// Protect The Wizard
IF
	ActionListEmpty()

	HPPercentGT(LastAttackerOf(PartySlot1),0)

	See(LastAttackerOf(PartySlot1))

	//HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)

	//See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71443) // Helping Wizard
		Continue()
END

// Help hurt allies
IF
	ActionListEmpty()

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	HPPercentLT(MostDamagedOf(Myself),80)
	HPPercentGT(LastAttackerOf(MostDamagedOf(Myself)),0)

	See(LastAttackerOf(MostDamagedOf(Myself)))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71424) // Helping Allies
		Continue()
END

// Attack Enemy Spellcasters
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

// Attack Enemy Spellcasters
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))

	HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
	See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

// Attack Enemy Spellcasters
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
	See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

// Attack Enemy Spellcasters
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))

	HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
	See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

// If attacked by an enemy attack them
IF 
	ActionListEmpty()

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
		!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	AttackedBy([ENEMY],DEFAULT)
	!AttackedBy([CHARMED],DEFAULT)
	!AttackedBy([REALLYCHARMED],DEFAULT)

	See(LastAttackerOf(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71425) // Attacking My Attacker
		Continue()
END

// Attack weakest enemy
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	HPPercentLT(NearestEnemyOf(Myself),50)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71426) // Attacking Weakest Enemy
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)

	HPPercentLT(SecondNearestEnemyOf(Myself),50)
	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71426) // Attacking Weakest Enemy
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)

	HPPercentLT(ThirdNearestEnemyOf(Myself),50)
	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71426) // Attacking Weakest Enemy
		Continue()
END

// Attack nearby enemies you can see
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	//OR(2)
	//	!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
	//	!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)
	!HPPercentLT(ThirdNearestEnemyOf(Myself),50)

	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71427) // Attacking Nearby Enemies
		Continue()
END

////////////////////////////////////////////////////////////////////////////////////// Offensive Spells On Target You Can See

// Level 3 - Evocation
IF
	Class(Myself,MAGE_ALL)
	HaveSpell(WIZARD_FIREBALL)
	!Range(FarthestEnemyOf(Myself),17)
	!StateCheck(FarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	TriggerOverride(FarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
	!TriggerOverride(FarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
	See(FarthestEnemyOf(Myself)) // Target the fireball target
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		SetGlobalTimer("castingfireball","LOCALS",6) // Starting fireball
		DisplayStringHead(Myself,71418) // Spell: Fireball
		Spell(FarthestEnemyOf(Myself),WIZARD_FIREBALL)
END

// Level 1 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MAGIC_MISSILE)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
	!ImmuneToSpellLevel(LastSeenBy(Myself),1)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71419) // Spell: Magic Missile
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Level 3 - Conjuration
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING) 
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71420) // Spell: Flame Arrow
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

// Level 2 - Conjuration
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING) 
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71421) // Spell: Melf Acid Arrow
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Level 2 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71422) // Spell: Agannazar Scorcher
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

// Level 3 - Necromancy
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLY_SMITE)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71423) // Spell: Holy Smite
		Spell(LastSeenBy(Myself),CLERIC_HOLY_SMITE)
END

//////////////////////////////////////////////////////////////////// Offensive Spells On Enemies You Cant See

// Level 1 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MAGIC_MISSILE)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),6,WIZARD_SPELL_IMMUNITY)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),1)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71419) // Spell: Magic Missile
		Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)
END

// Level 3 - Conjuration
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING) 
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),3)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(NearestEnemyOf(Myself),75,RESISTFIRE)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)

	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71420) // Spell: Flame Arrow
		Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)
END

// Level 2 - Conjuration
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING) 
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),2)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(NearestEnemyOf(Myself),75,RESISTACID)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71421) // Spell: Melf Acid Arrow
		Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)
END

// Level 2 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),6,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),2)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(NearestEnemyOf(Myself),75,RESISTFIRE)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71422) // Spell: Agannazar Scorcher
		Spell(NearestEnemyOf(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

// Level 3 - Necromancy
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLY_SMITE)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),3)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71423) // Spell: Holy Smite
		Spell(NearestEnemyOf(Myself),CLERIC_HOLY_SMITE)
END

//////////////////////////////////////////////////////////////////// Offensive Wands On Targets You Can See
IF
    ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand06",Myself)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSWANDS)
	OR(4)
		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
		CheckStatLT(LastSeenBy(Myself),10,THAC0)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71434) // Wand: Frost
		UseItem("wand06",LastSeenBy(Myself))
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand03",Myself)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSWANDS)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71431) // Wand: Magic Missile
		UseItem("wand03",LastSeenBy(Myself))
END

IF
  	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,CLERIC_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand11",Myself)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSWANDS)
	OR(4)
		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
		CheckStatLT(LastSeenBy(Myself),10,THAC0)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71437) // Wand: Heavens
		UseItem("wand11",LastSeenBy(Myself))
END

IF
	Class(Myself,MAGE_ALL)
	HasItem("wand05",Myself)
	!Range(FarthestEnemyOf(Myself),17)
	!StateCheck(FarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	TriggerOverride(FarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
	!TriggerOverride(FarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
	See(FarthestEnemyOf(Myself)) // Target the fireball target
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		SetGlobalTimer("castingfireball","LOCALS",6) // Starting fireball
		DisplayStringHead(Myself,71433) // Wand: Fire
		XEquipItem("wand05",Myself,SLOT_MISC0,EQUIP)
		UseItemSlotAbility(FarthestEnemyOf(Myself),SLOT_MISC0,0)
END

//IF
//	Class(Myself,MAGE_ALL)
//	HasItem("wand05",Myself)
	//!InLine(LastSeenBy(Myself),PartySlot1)
	//!InLine(LastSeenBy(Myself),PartySlot2)
	//!InLine(LastSeenBy(Myself),PartySlot3)
	//!InLine(LastSeenBy(Myself),PartySlot4)
	//!InLine(LastSeenBy(Myself),PartySlot5)
	//!InLine(LastSeenBy(Myself),PartySlot6)

//	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
//	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY) 
//	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
//	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

//	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
//	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
//	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

//	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
//	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

//	OR(4)
//		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
//		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
//		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
//		CheckStatLT(LastSeenBy(Myself),10,THAC0)
//	!InParty(LastSeenBy(Myself))
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		DisplayStringHead(Myself,71433) // Wand: Fire
//		XEquipItem("wand05",Myself,SLOT_MISC0,EQUIP)
//		UseItemSlotAbility(LastSeenBy(Myself),SLOT_MISC0,1)
//END

//IF
//  ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	Class(Myself,MAGE_ALL)
//	HasItem("wand10",Myself)
//	See(NearestEnemyOf(Myself))
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		DisplayStringHead(Myself,71436) // Wand: Monster Summoning
//		UseItem("wand10",LastSeenBy(Myself))
//END

//IF
//  ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	Class(Myself,MAGE_ALL)
//	HasItem("wand18",Myself)
//	See(NearestEnemyOf(Myself))
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		DisplayStringHead(Myself,71438) // Wand: Spell Striking
//		UseItem("wand18",LastSeenBy(Myself))
//END

//////////////////////////////////////////////////////////////////// Offensive Wands On Targets You Can't See
IF
    ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand06",Myself)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSWANDS)
	OR(4)
		CheckStatLT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
		CheckStatLT(NearestEnemyOf(Myself),0,ARMORCLASS)
		CheckStatGT(NearestEnemyOf(Myself),75,MAXHITPOINTS)
		CheckStatLT(NearestEnemyOf(Myself),10,THAC0)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71434) // Wand: Frost
		UseItem("wand06",NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand03",Myself)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSWANDS)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71431) // Wand: Magic Missile
		UseItem("wand03",NearestEnemyOf(Myself))
END

IF
  	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,CLERIC_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand11",Myself)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSWANDS)
	OR(4)
		CheckStatLT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
		CheckStatLT(NearestEnemyOf(Myself),0,ARMORCLASS)
		CheckStatGT(NearestEnemyOf(Myself),75,MAXHITPOINTS)
		CheckStatLT(NearestEnemyOf(Myself),10,THAC0)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		DisplayStringHead(Myself,71437) // Wand: Heavens
		UseItem("wand11",NearestEnemyOf(Myself))
END

//////////////////////////////////////////////////////////////////// Change Melee Weapon If Not Effective

//IF
//	ActionListEmpty()
//	//!GlobalTimerNotExpired("checkweapon0","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!CheckWeaponCanDamageV2(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON0,0)
//		//SetGlobalTimer("checkweapon0","LOCALS",20)
//END

//IF
//	ActionListEmpty()
//	//!GlobalTimerNotExpired("checkweapon1","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!WeaponCanDamage(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON1,0)
//		//SetGlobalTimer("checkweapon1","LOCALS",20)
//END

//IF
//	ActionListEmpty()
//	!GlobalTimerNotExpired("checkweapon2","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!WeaponCanDamage(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON2,0)
//		SetGlobalTimer("checkweapon2","LOCALS",20)
//END

//IF
//	ActionListEmpty()
//	!GlobalTimerNotExpired("checkweapon3","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!WeaponCanDamage(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON3,0)
//		SetGlobalTimer("checkweapon3","LOCALS",20)
//END

/////////////////////////////////////////////////////////// Equip Arrows If Out Of Ammo

//IF
//	!HasItemEquiped("AROW01",Myself)
//THEN
//	RESPONSE #100
///		DisplayStringHead(Myself,10)
//END

IF
	!HasItemEquiped("AROW01",Myself) // passing for both
	HasItemCategory(Myself,BOW,FALSE) // passing for both when false, neither when true
	HasItem("AROW01",Myself) // Arrow
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71467) // Equipping Arrows
		XEquipItem("AROW01",Myself,SLOT_AMMO0,EQUIP)
		Continue()
END

//	HasItem("AROW02",Myself) // Arrow + 1
//	HasItem("AROW03",Myself) // Arrow Of Slaying
//	HasItem("AROW04",Myself) // Acid Arrow + 1
//	HasItem("AROW05",Myself) // Arrow Of Biting
//	HasItem("AROW06",Myself) // Arrow Of Detonation
//	HasItem("AROW07",Myself) // Arrow Of Dispelling
//	HasItem("AROW08",Myself) // Arrow Of Fire + 2
//	HasItem("AROW09",Myself) // Arrow Of Ice
//	HasItem("AROW10",Myself) // Arrow Of Piercing + 1
//	HasItem("AROW11",Myself) // Arrow + 2
//	HasItem("AROW12",Myself) // Arrow Of Biting
//	HasItem("AROW14",Myself) // Poisoned Arrow
//	HasItem("AROW15",Myself) // Arrow Of Ice
//	HasItem("AROW16",Myself) // Arrow Of Ice
//	HasItem("ANGAROW",Myself) // Arrow Of Fire + 2
//	HasItem("AROW1A",Myself) // Arrow + 2
//	HasItem("AROWKC",Myself) // Arrow Of Fire + 2
//	HasItem("ARROPHE2",Myself) // Arrow Of Fire + 2
//	HasItem("bdarow01",Myself) // Arrow Of Antimagic + 1
//	HasItem("bdarow03",Myself) // Flaming Arrow
//	HasItem("bdarow04",Myself) // Arrow + 3
//	HasItem("CUTAROW1",Myself) // Arrow Of Ice
//	HasItem("IAROW01",Myself) // Arrow
//	HasItem("QUIV01",Myself) // Arrow

//////////////////////////////////////////////////////// Share Ammo

IF
	!HasItem("AROW01",Myself) // Arrow
	!HasItem("AROW02",Myself) // Arrow + 1
	!HasItem("AROW03",Myself) // Arrow Of Slaying
	!HasItem("AROW04",Myself) // Acid Arrow + 1
	!HasItem("AROW05",Myself) // Arrow Of Biting
	!HasItem("AROW06",Myself) // Arrow Of Detonation
	!HasItem("AROW07",Myself) // Arrow Of Dispelling
	!HasItem("AROW08",Myself) // Arrow Of Fire + 2
	!HasItem("AROW09",Myself) // Arrow Of Ice
	!HasItem("AROW10",Myself) // Arrow Of Piercing + 1
	!HasItem("AROW11",Myself) // Arrow + 2
	!HasItem("AROW12",Myself) // Arrow Of Biting
	!HasItem("AROW14",Myself) // Poisoned Arrow
	!HasItem("AROW15",Myself) // Arrow Of Ice
	!HasItem("AROW16",Myself) // Arrow Of Ice
	!HasItem("ANGAROW",Myself) // Arrow Of Fire + 2
	!HasItem("AROW1A",Myself) // Arrow + 2
	!HasItem("AROWKC",Myself) // Arrow Of Fire + 2
	!HasItem("ARROPHE2",Myself) // Arrow Of Fire + 2
	!HasItem("bdarow01",Myself) // Arrow Of Antimagic + 1
	!HasItem("bdarow03",Myself) // Flaming Arrow
	!HasItem("bdarow04",Myself) // Arrow + 3
	!HasItem("CUTAROW1",Myself) // Arrow Of Ice
	!HasItem("IAROW01",Myself) // Arrow
	!HasItem("QUIV01",Myself) // Arrow
	HasItemCategory(Myself,BOW,FALSE)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71465) // Help: Need Arrows
        Shout(NEED_ARROWS) // Shout for help
		Continue()
END

IF
    Heard([ANYONE],NEED_ARROWS) // If someone shouted for help
    !HasItem("AROW01",LastHeardBy(Myself))
	HasItem("AROW01",Myself)
THEN
    RESPONSE #100
		DisplayStringHead(Myself,71466) // Giving Arrows
        GiveItem("AROW01",LastHeardBy(Myself))
		Continue()
END

/////////////////////////////////////////////////////////// Change Ranged Ammo If Not Effective

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO0,0)
		Continue()
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO1,0)
		Continue()
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO2,0)
		Continue()
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO3,0)
		Continue()
END

/////////////////////////////////////////////////////////// Use Melfs Minute Meteors If Equipped

IF
	ActionListEmpty()
	HasItem("MELFMET",Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!InParty(LastSeenBy(Myself))

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71446) // Melfs Minute Meteors
		AttackOneRound(LastSeenBy(Myself))
END

///////////////////////////////////////////////////////// Melee/Ranged Non-Spell Attack
// Attack enemies that have been targeted
IF
	ActionListEmpty()
	//IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HPPercentGT(LastSeenBy(Myself),0)
	!InParty(LastSeenBy(Myself))
	//!Specifics(LastSeenBy(Myself),ALLIES)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// If cant see nearby enemy go and attack the nearest
IF
	ActionListEmpty()
	//IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

////////////////////////////////////////////////////////// Regroup if far away from each other
IF
	ActionListEmpty()
	NumInPartyGT(1)
	!Range(PartySlot2,80)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71428) // Regrouping
		MoveToObjectFollow(PartySlot2)
END

/////////////////////////////////////////////////////////// Remove Traps
IF
	ActionListEmpty()
	Class(Myself,THIEF_ALL)
  	OR(147)
		See("Door0146")
		See("Firedrake1")
		See("Firedrake2")
		See("Firedrake3")
		See("Firedrake4")
		See("Firedrake5")
		See("Firedrake6")
		See("Door1801")
		See("DOOR2012")
		See("Door2643")
		See("Door5401")
		See("Trigger Point 1")
		See("Dead Body")
		See("TranBD0101")
		See("TranBD0010")
		See("imoeninfo1")
		See("imoeninfo2")
		See("Bed_info")
		See("Info_SDD123")
		See("Tranbd0130rope")
		See("Tranbd0120rope")
		See("Lever_machine_stuck")
		See("TranBD1100")
		See("FORCEWALL")
		See("drawbridge_info")
		See("boaresky_blockade")
		See("BD2100GL")
		See("MDD1102")
		See("Lightningtrap")
		See("Hold_persontrap1")
		See("Flamestriketrap1")
		See("Speartrap1")
		See("Speartrap2")
		See("Speartrap3")
		See("Speartrap4")
		See("Speartrap5")
		See("Speartrap6")
		See("Speartrap7")
		See("Speartrap8")
		See("Speartrap9")
		See("Speartrap10")
		See("stone_icon")
		See("Wine Barrels")
		See("Mdd1233a")
		See("Mdd1233b")
		See("Mdd1233c")
		See("water_supplies")
		See("Infopoint16")
		See("TranBD4600")
		See("hidden_thief_cache")
		See("Trap 1")
		See("Info_ettin")
		See("BD4300Entrance")
		See("Lift_ropes")
		See("Dog Cage")
		See("belladonna1_inactive")
		See("belladonna1_active")
		See("belladonna2_inactive")
		See("belladonna2_active")
		See("belladonna3_inactive")
		See("belladonna3_active")
		See("dsc_gate_inner")
		See("TransBD4100")
		See("BD5200Entrance")
		See("TransBD4000")
		See("TransBD4300")
		See("InfoBDStairs")
		See("Infobdstairs_epilogue")
		See("Mdd1205")
		See("map_table")
		See("wall_breach")
		See("food_supplies")
		See("STAIRS")
		See("Light_Torch")
		See("Door02_info")
		See("Mask_wall")
		See("Mask1")
		See("Mask2")
		See("Mask3")
		See("Mask4")
		See("Mask5")
		See("Mask6")
		See("Phylactery2")
		See("Phylactery3")
		See("Phylactery4")
		See("Phylactery5")
		See("Phylactery6")
		See("BDPILL01")
		See("BDPILL02")
		See("BDPILL03")
		See("BDPILL04")
		See("Tranbd0062")
		See("Bd_pool")
		See("Ogre_cage1")
		See("Ogre_cage2")
		See("Ogre_cage3")
		See("Phylactery1")
		See("Jelly_globe01")
		See("Jelly_globe02")
		See("spidersilk1")
		See("spidersilk2")
		See("spidersilk3")
		See("spidersilk4")
		See("Infopoint06")
		See("Infravision_text")
		See("TransBD0067")
		//See("Hole_info")
		See("info_bridge")
		See("portal")
		See("Door4101a")
		See("GuardTrigger1")
		See("GuardTrigger2")
		See("GuardTrigger3")
		See("GuardTrigger4")
		See("RILSATRIGGER")
		See("GREASETRAP")
		See("ARROWTRAP1")
		See("ARROWTRAP2")
		See("ARROWTRAP3")
		See("ARROWTRAP4")
		See("ARROWTRAP5")
		See("ARROWTRAP6")
		See("STINKYTRAP")
		See("JERKTRAP")
		See("Door0200")
		See("Door0109a")
		See("Door0109b")
		See("Door0111")
		See("Bullrushtrap")
		See("Itachtrap")
		See("Meialatrap")
		See("Moorlochtrap")
		See("deathtrap1")
		See("deathtrap2")
		See("deathtrap3")
		See("Tarnortrap")
		See("TRAN0016a")
		See("TRAN0016b")
		See("TRAN0018")
		See("INFO0016a")
		See("INFO0016b")
		See("INFO0018")
		See("TRAN0017a")
		See("TRAN0017b")
		See("INFO0017a")
		See("INFO0017b")
		See("Teleport1")
		See("Teleport2")
THEN
  RESPONSE #100
  		DisplayStringHead(Myself,71468) // Removing Traps
    	RemoveTraps(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////// Find traps
IF
	ActionListEmpty()
	Class(Myself,THIEF_ALL)
	!ModalState(DETECTTRAPS)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,71429) // Finding Traps
		FindTraps()
END

////////////////////////////////////////////////////////// Randomly turn around, makes them look more alive
//IF
//	ActionListEmpty()
//THEN
//	RESPONSE #100
//		DisplayStringHead(Myself,1539)
//		RandomTurn()
//		ClearAllActions()
//END

//IF
//
//THEN
//	RESPONSE #25
//		MoveToOffset([1.1])
//	RESPONSE #25
//		MoveToOffset([1.-1])
//	RESPONSE #25
//		MoveToOffset([-1.1])
//	RESPONSE #25
//		MoveToOffset([-1.-1])
//END