////////////////////////////////////////////////////////////////// Cancel Melee If AI Ranged Has Run Out Of Ammo And Can See An Enemy

// AIRanged can sometimes still use melee if their ranged weapon suddenly runs out of ammo and continue to attack the enemy with melee for the rest of the round
// This bit ensures that AIRanged cancel their normal attack if their ranged weapon is out of ammo and don't use melee.
// The HP check allows them to move closer if the enemy if far away but not if they are close by.

IF
	Global("usingNormalAttack","LOCALS",1)
	!IsWeaponRanged(Myself)
	HPGT(NearestEnemyOf(Myself),0)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71499) // Clearing Actions
		SetGlobal("usingNormalAttack","LOCALS",0)
		ClearAllActions()
		Continue()
END

////////////////////////////////////////////////////////////////// Cancel Fireball If Enemy Has Moved Closer
// If casting a fireball and target is within 17ft cancel it
IF
	GlobalTimerNotExpired("castingfireball","LOCALS")
	Range(LastSeenBy(Myself),17)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71459) // Cancelling Fireball
		SetGlobalTimer("castingfireball","LOCALS",0)
		ClearAllActions()
END

// If casting fireball and target still far away, continue until cast and don't continue with other actions
IF
	GlobalTimerNotExpired("castingfireball","LOCALS")
THEN
	RESPONSE #100
		// Continue with current action
END

////////////////////////////////////////////////////////////////// Status Messages

IF
	!GlobalTimerNotExpired("energyleveldrained","LOCALS")
	CheckStatGT(Myself,0,LEVELDRAIN)
THEN
	RESPONSE #100
		SetGlobalTimer("energyleveldrained","LOCALS",30)
		//DisplayStringHead(Myself,71451) // Status: Energy Level Drained
		Continue()
END

IF
	!GlobalTimerNotExpired("fatigued","LOCALS")
	CheckStatGT(Myself,0,FATIGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("fatigued","LOCALS",30)
		//DisplayStringHead(Myself,71488) // Status: Fatigued
		Continue()
END

////////////////////////////////////////////////////////////////// Take Note Of My Current Weapon So I Can Switch Back To It

//IF
//
//THEN
//	RESPONSE #100
//		
//		//DisplayStringHead(Myself,10)
//END

// FillSlot(SLOT_WEAPON0) Equips the next available item in your inventory replacing what you currently have equipped and swapping between just those two weapons.

// Note: You can only save to global variables, so we have one variable for each member in your party.
// We save the currently equipped weapon to a variable so you can switch back to it later.
// Only save our weapon if we haven't already switched our weapon.

// PartySlot1
//IF
//	Global("PartySlot1SwitchedWeapon","LOCAL",0) // 0 false, 1 true
//THEN
//	RESPONSE #100
//		SetTokenObject("PartySlot1OriginalWeapon",Myself)
//END
//

//  [EA.GENERAL.RACE.CLASS.SPECIFIC.GENDER.ALIGN]
//  [ALLY.0.0.0.0.SUMMONED.0]



////////////////////////////////////////////////////////////////// If poisoned use an antidote potion
IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	StateCheck(Myself,STATE_POISONED) 
	HasItem("potn20",Myself)  // Antidote
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71380) // Potion: Antidote
		UseItem("potn20",Myself)  // Antidote
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	StateCheck(Myself,STATE_POISONED)
	HasItem("potn17",Myself)  // Elixir of health - cures disease and poisons
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71381) // Potion: Elixir Of Health
		UseItem("potn17",Myself)  // Elixir of health - cures disease and poisons
END

////////////////////////////////////////////////////////////////// Share Antidotes

IF
    StateCheck(Myself,STATE_POISONED)
	!HasItem("potn17",Myself)
    !HasItem("potn20",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71462) // Help: Need Antidote
        Shout(NEED_ANTIDOTE) // Shout for help
		Continue()
END

IF
    Heard([ANYONE],NEED_ANTIDOTE) // If someone shouted for help
    !HasItem("potn20",LastHeardBy(Myself))
	!HasItem("potn17",LastHeardBy(Myself))
	HasItem("potn20",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71463) // Giving Antidote
        GiveItem("potn20",LastHeardBy(Myself))
		Continue()
END

IF
    Heard([ANYONE],NEED_ANTIDOTE) // If someone shouted for help
    !HasItem("potn20",LastHeardBy(Myself))
	!HasItem("potn17",LastHeardBy(Myself))
	HasItem("potn17",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71463) // Giving Antidote
        GiveItem("potn17",LastHeardBy(Myself))
		Continue()
END

////////////////////////////////////////////////////////////////////////////////////// Use Cure Disease Potions

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	StateCheck(Myself,STATE_DISEASED) 
	HasItem("potn17",Myself)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71381) // Potion: Elixir Of Health
		UseItem("potn17",Myself)
END

////////////////////////////////////////////////////////////////////////////////////// Share Cure Disease Potions

IF
    StateCheck(Myself,STATE_DISEASED)
	!HasItem("potn17",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71489) // Help: Need Cure Disease
        Shout(NEED_CURE_DISEASE) // Shout for help
		Continue()
END

IF
    Heard([ANYONE],NEED_CURE_DISEASE) // If someone shouted for help
	!HasItem("potn17",LastHeardBy(Myself))
	HasItem("potn17",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71490) // Giving Elixir Of Health
        GiveItem("potn17",LastHeardBy(Myself))
		Continue()
END

////////////////////////////////////////////////////////////////////////////////////// Buff Potions

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	OR(2)
		HitBy([ENEMY],FIRE)
		HitBy([ENEMY],MAGICFIRE)
	DamageTakenGT(25)
	HasItem("potn02",Myself)
	CheckStatLT(Myself,49,RESISTFIRE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71447) // Potion: Fire Resistance
		UseItem("potn02",Myself)
END

IF
	OR(2)
		HitBy([ENEMY],FIRE)
		HitBy([ENEMY],MAGICFIRE)
	DamageTakenGT(25)
	!HasItem("potn02",Myself)
	CheckStatLT(Myself,49,RESISTFIRE)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71475) // Help: Need Potion Fire Resistance
        Shout(NEED_POTION_FIRE_RESISTANCE) // Shout for help
		Continue()
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	OR(2)
		HitBy([ENEMY],COLD)
		HitBy([ENEMY],MAGICCOLD)
	DamageTakenGT(25)
	HasItem("potn22",Myself)
	CheckStatLT(Myself,49,RESISTCOLD)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71448) // Potion: Cold Resistance
		UseItem("potn22",Myself)
END

IF
	OR(2)
		HitBy([ENEMY],COLD)
		HitBy([ENEMY],MAGICCOLD)
	DamageTakenGT(25)
	!HasItem("potn22",Myself)
	CheckStatLT(Myself,49,RESISTCOLD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71476) // Help: Need Potion Cold Resistance
        Shout(NEED_POTION_COLD_RESISTANCE) // Shout for help
		Continue()
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HitBy([ENEMY],ELECTRICITY)
	DamageTakenGT(25)
	HasItem("potn31",Myself)
	CheckStatLT(Myself,49,RESISTELECTRICITY)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71449) // Potion: Insulation
		UseItem("potn31",Myself)
END

IF
	HitBy([ENEMY],ELECTRICITY)
	DamageTakenGT(25)
	!HasItem("potn31",Myself)
	CheckStatLT(Myself,49,RESISTELECTRICITY)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71477) // Help: Need Potion Insulation
        Shout(NEED_POTION_INSULATION) // Shout for help
		Continue()
END

//////////////////////////////////////////////////////////////////// Share Buff Potions

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_POTION_FIRE_RESISTANCE) // If someone shouted for help
    !HasItem("potn02",LastHeardBy(Myself))
	HasItem("potn02",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71472) // Giving Potion Fire Resistance
        GiveItem("potn02",LastHeardBy(Myself))
		Continue()
END

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_POTION_COLD_RESISTANCE) // If someone shouted for help
    !HasItem("potn22",LastHeardBy(Myself))
	HasItem("potn22",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71473) // Giving Potion Cold Resistance
        GiveItem("potn22",LastHeardBy(Myself))
		Continue()
END

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_POTION_INSULATION) // If someone shouted for help
    !HasItem("potn31",LastHeardBy(Myself))
	HasItem("potn31",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71474) // Giving Potion Insulation
        GiveItem("potn31",LastHeardBy(Myself))
		Continue()
END

//////////////////////////////////////////////////////////////////// If ally health is low and have heal spell, heal them
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),80)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71375) // Spell: Cure Light Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_LIGHT_WOUNDS)
END

//IF
//	ActionListEmpty()
//  !GlobalTimerNotExpired("castnattack","LOCALS")
//	HaveSpell(INNATE_CURE_LIGHT_WOUNDS)
//	HPPercentLT(MostDamagedOf(Myself),80)
//	!Class(Myself,MAGE_ALL)
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71375) // Spell: Cure Light Wounds
//		Spell(MostDamagedOf(Myself),INNATE_CURE_LIGHT_WOUNDS)
//END

//IF
//	ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	HaveSpell(INNATE_CURE_LIGHT_WOUNDS)
//	HPPercentLT(Myself,80)
//	Class(Myself,MAGE_ALL)
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71375) // Spell: Cure Light Wounds
//		Spell(Myself,INNATE_CURE_LIGHT_WOUNDS)
//END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),80) 

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71376) // Spell: Cure Medium Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),75)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71377) // Spell: Cure Serious Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_SERIOUS_WOUNDS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
	HPPercentLT(MostDamagedOf(Myself),70)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71500) // Spell: Cure Critical Wounds
		Spell(MostDamagedOf(Myself),CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
	HPPercentLT(MostDamagedOf(Myself),70)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
		SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71461) // Spell: Mass Cure
		Spell(MostDamagedOf(Myself),CLERIC_MASS_CURE)
END

/////////////////////////////////////////////////////////////////// If health is low use a healing potion

// check hp < maxhp - 27
// per = hp/maxhp*100
// hp > 27*per/(100-per)
// if per < x and hp > 27*x/(100-x)

// Potion 52 - Potion Of Extra Healing

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,10) 
	HPGT(Myself,3)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,20) 
	HPGT(Myself,7)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,30) 
	HPGT(Myself,12)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,40) 
	HPGT(Myself,18)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,50) 
	HPGT(Myself,27)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,60) 
	HPGT(Myself,41)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71379) // Potion: Extra Healing
		UseItem("potn52",Myself)  // Potion of Extra Healing
END

// check hp <= maxhp - 9
// per = hp/maxhp*100
// hp >= 9*per/(100-per)
// if per < x and hp > 9*x/(100-x)

// Potion 8 - Potion Of Healing

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,10) 
	HPGT(Myself,1)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,20) 
	HPGT(Myself,2)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,30) 
	HPGT(Myself,4)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,40) 
	HPGT(Myself,6)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,50) 
	HPGT(Myself,9)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,60) 
	HPGT(Myself,14)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn08",Myself)  // Potion of Healing
	HPPercentLT(Myself,70) 
	HPGT(Myself,21)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn08",Myself)  // Potion of Healing
END

// Potion 25 - Potion Of Healing

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,10) 
	HPGT(Myself,1)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,20) 
	HPGT(Myself,2)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,30) 
	HPGT(Myself,4)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,40) 
	HPGT(Myself,6)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,50) 
	HPGT(Myself,9)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,60) 
	HPGT(Myself,14)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

IF 
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("potn25",Myself)  // Potion of Healing
	HPPercentLT(Myself,70) 
	HPGT(Myself,21)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71378) // Potion: Healing
		UseItem("potn25",Myself)  // Potion of Healing
END

////////////////////////////////////////////////////////////////// Share Healing Potions

IF
	ActionListEmpty()
    !HasItem("potn08",Myself)
    HPPercentLT(Myself,50)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71457) // Help: Need Potion Of Healing
        Shout(NEED_POTION_OF_HEALING) // Shout for help
		Continue()
END

IF
	ActionListEmpty()
    Heard([ANYONE],NEED_POTION_OF_HEALING) // If someone shouted for help
    !HasItem("potn08",LastHeardBy(Myself))
	HasItem("potn08",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71458) // Giving Healing Potion
        GiveItem("potn08",LastHeardBy(Myself)) // Pass them the item
		Continue()
END

//////////////////////////////////////////////////////////////// Healing Scrolls

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL56",Myself)
	HPPercentLT(MostDamagedOf(Myself),75)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71506) // Scroll: Cure Serious Wounds
		UseItem("SCRL56",MostDamagedOf(Myself))
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL61",Myself)
	HPPercentLT(MostDamagedOf(Myself),75)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71501) // Scroll: Cure Critical Wounds
		UseItem("SCRL61",MostDamagedOf(Myself))
END

//////////////////////////////////////////////////////////////// Restoration Spells
// Restoration spells undo level drain

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_LESSER_RESTORATION)
	CheckStatGT(PartySlot1,0,LEVELDRAIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Lesser Restoration
		Spell(PartySlot1,CLERIC_LESSER_RESTORATION)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_LESSER_RESTORATION)
	CheckStatGT(PartySlot2,0,LEVELDRAIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Lesser Restoration
		Spell(PartySlot2,CLERIC_LESSER_RESTORATION)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_LESSER_RESTORATION)
	CheckStatGT(PartySlot3,0,LEVELDRAIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Lesser Restoration
		Spell(PartySlot3,CLERIC_LESSER_RESTORATION)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_LESSER_RESTORATION)
	CheckStatGT(PartySlot4,0,LEVELDRAIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Lesser Restoration
		Spell(PartySlot4,CLERIC_LESSER_RESTORATION)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_LESSER_RESTORATION)
	CheckStatGT(PartySlot5,0,LEVELDRAIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Lesser Restoration
		Spell(PartySlot5,CLERIC_LESSER_RESTORATION)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_LESSER_RESTORATION)
	CheckStatGT(PartySlot6,0,LEVELDRAIN)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Lesser Restoration
		Spell(PartySlot6,CLERIC_LESSER_RESTORATION)
END

//////////////////////////////////////////////////////////////// Run away from nearby enemies if health is low
// If an enemy is nearby and the same location timer isn't running, then start the timer and run away
IF 
	ActionListEmpty()
	!GlobalTimerExpired("locMeSame","LOCALS")
	!GlobalTimerNotExpired("locMeSame","LOCALS")
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71382) // Running Away
		SetGlobalTimer("locMeSame","LOCALS",3)
		RunAwayFrom(NearestEnemyOf(Myself),20)
END

IF 
	ActionListEmpty()
	!GlobalTimerExpired("locMeSame","LOCALS")
	!GlobalTimerNotExpired("locMeSame","LOCALS")
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71382) // Running Away
		SetGlobalTimer("locMeSame","LOCALS",3)
		RunAwayFrom(NearestEnemyOf(Myself),25)
END

// If an enemy is nearby and the same location timer is running but hasn't expired, then run away
IF 
	ActionListEmpty()
	GlobalTimerNotExpired("locMeSame","LOCALS")
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71382) // Running Away
		RunAwayFrom(NearestEnemyOf(Myself),15)
END

// If an enemy is nearby and the same location timer has expired (have been in the same spot for a while), continue with normal actions and attack

////////////////////////////////////////////////////////////////////////////////////// Counter Silence

// Level 2 - Abjuration 1
// 10 rounds (60 seconds) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_VOCALIZE)
	StateCheck(Myself,STATE_SILENCED)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71508) // Spell: Vocalize
		Spell(Myself,WIZARD_VOCALIZE)
END

////////////////////////////////////////////////////////////////////////////////////// Spell Shields

// Level 3
// 3 Rounds/Level (18 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
	!CheckStat(Myself,1,WIZARD_SPELL_DEFLECTION)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71416) // Spell: Minor Spell Deflection
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

// Level 6
// 3 Rounds/Level (18 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SPELL_DEFLECTION)
	!CheckStat(Myself,1,WIZARD_SPELL_DEFLECTION)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71491) // Spell: Spell Deflection
		Spell(Myself,WIZARD_SPELL_DEFLECTION)
END

// Level 5
// 3 Rounds/Level (18 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MINOR_SPELL_TURNING)
	!CheckStat(Myself,1,WIZARD_SPELL_TURNING)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71492) // Spell: Minor Spell Turning
		Spell(Myself,WIZARD_MINOR_SPELL_TURNING)
END

// Level 7
// 3 Rounds/Level (18 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SPELL_TURNING)
	!CheckStat(Myself,1,WIZARD_SPELL_TURNING)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71493) // Spell: Spell Turning
		Spell(Myself,WIZARD_SPELL_TURNING)
END

// Level 4
// 1 Round/Level (6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
	!CheckStat(Myself,1,MINORGLOBE)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71415) // Spell: Minor Globe Of Invulnerability
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END

////////////////////////////////////////////////////////////////////////////////////// Scrolls: Spell Shields

// Level 3
// 3 Rounds/Level (18 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL6G",Myself)
	!CheckStat(Myself,1,WIZARD_SPELL_DEFLECTION)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71416) // Spell: Minor Spell Deflection
		UseItem("SCRL6G",Myself)
END

// Level 5
// 3 Rounds/Level (18 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL7D",Myself)
	!CheckStat(Myself,1,WIZARD_SPELL_TURNING)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71492) // Spell: Minor Spell Turning
		UseItem("SCRL7D",Myself)
END

// Level 4
// 1 Round/Level (6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL1Z",Myself)
	!CheckStat(Myself,1,MINORGLOBE)

	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71415) // Spell: Minor Globe Of Invulnerability
		UseItem("SCRL1Z",Myself)
END

////////////////////////////////////////////////////////////////////////////////////// Debuff/Control Spells
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	OR(9)
		SpellCast([ANYONE],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([ANYONE],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([ANYONE],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([ANYONE],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([ANYONE],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([ANYONE],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([ANYONE],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([ANYONE],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([ANYONE],CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
		SpellCast([ANYONE],TRAP_STINKING_CLOUD)
		SpellCast([ANYONE],TRAP_CLOUDKILL)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
		SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71442) // Spell: Zone Of Sweet Air
		Spell(Myself,CLERIC_ZONE_OF_SWEET_AIR)
END

// Level 2 - Alteration
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Silence, 15' Radius)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71383) // Spell: Silence
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)  // SPPR211.SPL (Silence, 15' Radius)
END

// Level 6 - Abjuration 1
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_PIERCE_MAGIC)
	See(NearestEnemyOf(Myself))

	OR(12)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),5,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),60,RESISTMAGIC)

	!ImmuneToSpellLevel(LastSeenBy(Myself),6)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71507) // Spell: Pierce Magic
		Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)
END

// Level 5 - Abjuration 1
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_LOWER_RESISTANCE)
	See(NearestEnemyOf(Myself))

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)

	!ImmuneToSpellLevel(LastSeenBy(Myself),5)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71485) // Spell: Lower Resistance
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

// Level 4 - Abjuration
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SECRET_WORD)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!ImmuneToSpellLevel(LastSeenBy(Myself),4)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71384) // Spell: Secret Word
		Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)
END

// Level 2 - Divination
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)
	OR(2)
		SpellCast([EVILCUTOFF],WIZARD_INVISIBILITY)
		SpellCast([EVILCUTOFF],WIZARD_IMPROVED_INVISIBILITY)
	!ImmuneToSpellLevel(LastTrigger,2)
	!CheckStat(LastTrigger,1,MINORGLOBE)
	!CheckStat(LastTrigger,1,WIZARD_SPELL_TURNING)
	!CheckStat(LastTrigger,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(LastTrigger,3,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71450) // Spell: Detect Invisibility
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)
END

// Level 2 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)
	See([EVILCUTOFF.HUMANOID])
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71460) // Spell: Hold Person
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

// Level 1 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SLEEP)
	See([EVILCUTOFF.HUMANOID])
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),1)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71487) // Spell: Sleep
		Spell(LastSeenBy(Myself),WIZARD_SLEEP)
END


// Level 3 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HOLD_PERSON)
	See([EVILCUTOFF.HUMANOID])
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71460) // Spell: Hold Person
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

// Level 5 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HOLD_MONSTER)
	See(NearestEnemyOf(Myself))
	!CheckSpellState(LastSeenBy(Myself),HELD)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),5)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
	!CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
	!CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71385) // Spell: Hold Monster
		Spell(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)
END

// Level 5 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_CHAOS)  // SPPR211.SPL (Silence, 15' Radius)
	NumCreatureVsPartyGT(Myself,3)

	!StateCheck(NearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(NearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),5)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)	
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),5)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	CheckStatGT(SecondNearestEnemyOf(Myself),5,SAVEVSSPELL)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),5)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	CheckStatGT(ThirdNearestEnemyOf(Myself),5,SAVEVSSPELL)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DEBUFF)
	!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),5)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	CheckStatGT(FourthNearestEnemyOf(Myself),5,SAVEVSSPELL)

	See(NearestEnemyOf(Myself))

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71386) // Spell: Chaos
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)
END

// Level 2 - Necromancy
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_HORROR)
	NumCreatureVsPartyGT(Myself,4)

	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),2)
	!CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	!Race(NearestEnemyOf(Myself),DEMONIC)
	!Kit(NearestEnemyOf(Myself),CAVALIER)
	!Kit(NearestEnemyOf(Myself),Blackguard)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),2)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(SecondNearestEnemyOf(Myself),UNDEAD)
	!Race(SecondNearestEnemyOf(Myself),DEMONIC)
	!Kit(SecondNearestEnemyOf(Myself),CAVALIER)
	!Kit(SecondNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(SecondNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),2)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(ThirdNearestEnemyOf(Myself),UNDEAD)
	!Race(ThirdNearestEnemyOf(Myself),DEMONIC)
	!Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
	!Kit(ThirdNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(ThirdNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),2)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FourthNearestEnemyOf(Myself),UNDEAD)
	!Race(FourthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FourthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FourthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FourthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FifthNearestEnemyOf(Myself),2)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FifthNearestEnemyOf(Myself),UNDEAD)
	!Race(FifthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FifthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FifthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FifthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71387) // Spell: Horror
		Spell(NearestEnemyOf(Myself),WIZARD_HORROR)
END


// Dispel Magic On Enemies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_BREACH)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),5)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71452) // Spell: Breach
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

// Wizard True Dispel Magic = Dispel Magic
// Dispel Magic On Allies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot1,HOPELESSNESS)
		CheckSpellState(PartySlot1,ENFEEBLED)
		CheckSpellState(PartySlot1,HELD)
		CheckSpellState(PartySlot1,ENTANGLE)
		CheckSpellState(PartySlot1,WEB)
		CheckSpellState(PartySlot1,DOOM)
		CheckSpellState(PartySlot1,MISCAST_MAGIC)
		StateCheck(PartySlot1,STATE_PANIC)
		StateCheck(PartySlot1,STATE_CHARMED)
		StateCheck(PartySlot1,STATE_CONFUSED)
		StateCheck(PartySlot1,STATE_SLEEPING)
		StateCheck(PartySlot1,STATE_SLOWED)
		StateCheck(PartySlot1,STATE_FEEBLEMINDED)
	See(PartySlot1)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot2,HOPELESSNESS)
		CheckSpellState(PartySlot2,ENFEEBLED)
		CheckSpellState(PartySlot2,HELD)
		CheckSpellState(PartySlot2,ENTANGLE)
		CheckSpellState(PartySlot2,WEB)
		CheckSpellState(PartySlot2,DOOM)
		CheckSpellState(PartySlot2,MISCAST_MAGIC)
		StateCheck(PartySlot2,STATE_PANIC)
		StateCheck(PartySlot2,STATE_CHARMED)
		StateCheck(PartySlot2,STATE_CONFUSED)
		StateCheck(PartySlot2,STATE_SLEEPING)
		StateCheck(PartySlot2,STATE_SLOWED)
		StateCheck(PartySlot2,STATE_FEEBLEMINDED)
	See(PartySlot2)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot3,HOPELESSNESS)
		CheckSpellState(PartySlot3,ENFEEBLED)
		CheckSpellState(PartySlot3,HELD)
		CheckSpellState(PartySlot3,ENTANGLE)
		CheckSpellState(PartySlot3,WEB)
		CheckSpellState(PartySlot3,DOOM)
		CheckSpellState(PartySlot3,MISCAST_MAGIC)
		StateCheck(PartySlot3,STATE_PANIC)
		StateCheck(PartySlot3,STATE_CHARMED)
		StateCheck(PartySlot3,STATE_CONFUSED)
		StateCheck(PartySlot3,STATE_SLEEPING)
		StateCheck(PartySlot3,STATE_SLOWED)
		StateCheck(PartySlot3,STATE_FEEBLEMINDED)
	See(PartySlot3)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot4,HOPELESSNESS)
		CheckSpellState(PartySlot4,ENFEEBLED)
		CheckSpellState(PartySlot4,HELD)
		CheckSpellState(PartySlot4,ENTANGLE)
		CheckSpellState(PartySlot4,WEB)
		CheckSpellState(PartySlot4,DOOM)
		CheckSpellState(PartySlot4,MISCAST_MAGIC)
		StateCheck(PartySlot4,STATE_PANIC)
		StateCheck(PartySlot4,STATE_CHARMED)
		StateCheck(PartySlot4,STATE_CONFUSED)
		StateCheck(PartySlot4,STATE_SLEEPING)
		StateCheck(PartySlot4,STATE_SLOWED)
		StateCheck(PartySlot4,STATE_FEEBLEMINDED)
	See(PartySlot4)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot5,HOPELESSNESS)
		CheckSpellState(PartySlot5,ENFEEBLED)
		CheckSpellState(PartySlot5,HELD)
		CheckSpellState(PartySlot5,ENTANGLE)
		CheckSpellState(PartySlot5,WEB)
		CheckSpellState(PartySlot5,DOOM)
		CheckSpellState(PartySlot5,MISCAST_MAGIC)
		StateCheck(PartySlot5,STATE_PANIC)
		StateCheck(PartySlot5,STATE_CHARMED)
		StateCheck(PartySlot5,STATE_CONFUSED)
		StateCheck(PartySlot5,STATE_SLEEPING)
		StateCheck(PartySlot5,STATE_SLOWED)
		StateCheck(PartySlot5,STATE_FEEBLEMINDED)
	See(PartySlot5)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot6,HOPELESSNESS)
		CheckSpellState(PartySlot6,ENFEEBLED)
		CheckSpellState(PartySlot6,HELD)
		CheckSpellState(PartySlot6,ENTANGLE)
		CheckSpellState(PartySlot6,WEB)
		CheckSpellState(PartySlot6,DOOM)
		CheckSpellState(PartySlot6,MISCAST_MAGIC)
		StateCheck(PartySlot6,STATE_PANIC)
		StateCheck(PartySlot6,STATE_CHARMED)
		StateCheck(PartySlot6,STATE_CONFUSED)
		StateCheck(PartySlot6,STATE_SLEEPING)
		StateCheck(PartySlot6,STATE_SLOWED)
		StateCheck(PartySlot6,STATE_FEEBLEMINDED)
	See(PartySlot6)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

// Dispel Magic On Enemies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ENEMY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ENEMY)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

// Wizard Dispel Magic = Remove Magic
// Level 3 - Abjuration
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ENEMY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71388) // Spell: Remove Magic
		Shout(CASTING_DISPEL_MAGIC_ENEMY)
		Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

// Cleric Dispel Magic = Dispel Magic
// Level 3 - Abjuration
// Dispel Magic On Allies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot1,HOPELESSNESS)
		CheckSpellState(PartySlot1,ENFEEBLED)
		CheckSpellState(PartySlot1,HELD)
		CheckSpellState(PartySlot1,ENTANGLE)
		CheckSpellState(PartySlot1,WEB)
		CheckSpellState(PartySlot1,DOOM)
		CheckSpellState(PartySlot1,MISCAST_MAGIC)
		StateCheck(PartySlot1,STATE_PANIC)
		StateCheck(PartySlot1,STATE_CHARMED)
		StateCheck(PartySlot1,STATE_CONFUSED)
		StateCheck(PartySlot1,STATE_SLEEPING)
		StateCheck(PartySlot1,STATE_SLOWED)
		StateCheck(PartySlot1,STATE_FEEBLEMINDED)
	See(PartySlot1)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot2,HOPELESSNESS)
		CheckSpellState(PartySlot2,ENFEEBLED)
		CheckSpellState(PartySlot2,HELD)
		CheckSpellState(PartySlot2,ENTANGLE)
		CheckSpellState(PartySlot2,WEB)
		CheckSpellState(PartySlot2,DOOM)
		CheckSpellState(PartySlot2,MISCAST_MAGIC)
		StateCheck(PartySlot2,STATE_PANIC)
		StateCheck(PartySlot2,STATE_CHARMED)
		StateCheck(PartySlot2,STATE_CONFUSED)
		StateCheck(PartySlot2,STATE_SLEEPING)
		StateCheck(PartySlot2,STATE_SLOWED)
		StateCheck(PartySlot2,STATE_FEEBLEMINDED)
	See(PartySlot2)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot3,HOPELESSNESS)
		CheckSpellState(PartySlot3,ENFEEBLED)
		CheckSpellState(PartySlot3,HELD)
		CheckSpellState(PartySlot3,ENTANGLE)
		CheckSpellState(PartySlot3,WEB)
		CheckSpellState(PartySlot3,DOOM)
		CheckSpellState(PartySlot3,MISCAST_MAGIC)
		StateCheck(PartySlot3,STATE_PANIC)
		StateCheck(PartySlot3,STATE_CHARMED)
		StateCheck(PartySlot3,STATE_CONFUSED)
		StateCheck(PartySlot3,STATE_SLEEPING)
		StateCheck(PartySlot3,STATE_SLOWED)
		StateCheck(PartySlot3,STATE_FEEBLEMINDED)
	See(PartySlot3)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot4,HOPELESSNESS)
		CheckSpellState(PartySlot4,ENFEEBLED)
		CheckSpellState(PartySlot4,HELD)
		CheckSpellState(PartySlot4,ENTANGLE)
		CheckSpellState(PartySlot4,WEB)
		CheckSpellState(PartySlot4,DOOM)
		CheckSpellState(PartySlot4,MISCAST_MAGIC)
		StateCheck(PartySlot4,STATE_PANIC)
		StateCheck(PartySlot4,STATE_CHARMED)
		StateCheck(PartySlot4,STATE_CONFUSED)
		StateCheck(PartySlot4,STATE_SLEEPING)
		StateCheck(PartySlot4,STATE_SLOWED)
		StateCheck(PartySlot4,STATE_FEEBLEMINDED)
	See(PartySlot4)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot5,HOPELESSNESS)
		CheckSpellState(PartySlot5,ENFEEBLED)
		CheckSpellState(PartySlot5,HELD)
		CheckSpellState(PartySlot5,ENTANGLE)
		CheckSpellState(PartySlot5,WEB)
		CheckSpellState(PartySlot5,DOOM)
		CheckSpellState(PartySlot5,MISCAST_MAGIC)
		StateCheck(PartySlot5,STATE_PANIC)
		StateCheck(PartySlot5,STATE_CHARMED)
		StateCheck(PartySlot5,STATE_CONFUSED)
		StateCheck(PartySlot5,STATE_SLEEPING)
		StateCheck(PartySlot5,STATE_SLOWED)
		StateCheck(PartySlot5,STATE_FEEBLEMINDED)
	See(PartySlot5)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(11)
		CheckSpellState(PartySlot6,HOPELESSNESS)
		CheckSpellState(PartySlot6,ENFEEBLED)
		CheckSpellState(PartySlot6,HELD)
		CheckSpellState(PartySlot6,ENTANGLE)
		CheckSpellState(PartySlot6,WEB)
		CheckSpellState(PartySlot6,DOOM)
		CheckSpellState(PartySlot6,MISCAST_MAGIC)
		StateCheck(PartySlot6,STATE_PANIC)
		StateCheck(PartySlot6,STATE_CHARMED)
		StateCheck(PartySlot6,STATE_CONFUSED)
		StateCheck(PartySlot6,STATE_SLEEPING)
		StateCheck(PartySlot6,STATE_SLOWED)
		StateCheck(PartySlot6,STATE_FEEBLEMINDED)
	See(PartySlot6)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ALLY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ALLY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

// Dispel Magic On Enemies
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DISPEL_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(26)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SHIELDGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),POTION_OF_MAGIC_BLOCKING)
		CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
		CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
		CheckSpellState(LastSeenBy(Myself),BUFF_PRO_EFFECTS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_BLESS)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
		StateCheck(LastSeenBy(Myself),STATE_BLUR)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!Heard([ANYONE],CASTING_DISPEL_MAGIC_ENEMY)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71389) // Spell: Dispel Magic
		Shout(CASTING_DISPEL_MAGIC_ENEMY)
		Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)
END

// Level 3 - Enchantment
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_MISCAST_MAGIC)
	OR(4)
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	!CheckSpellState(LastSeenBy(Myself),MISCAST_MAGIC)
	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71390) // Spell: Miscast Magic
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END

IF
 	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DOOM)
	See(NearestEnemyOf(Myself))
	OR(4)
		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
		CheckStatLT(LastSeenBy(Myself),10,THAC0)
	!CheckSpellState(LastSeenBy(Myself),DOOM)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71439) // Spell: Doom
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)
	See(NearestEnemyOf(Myself))
	!CheckSpellState(NearestEnemyOf(Myself),MALISON)
	OR(4)
		CheckStatLT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
		CheckStatLT(NearestEnemyOf(Myself),0,ARMORCLASS)
		CheckStatGT(NearestEnemyOf(Myself),75,MAXHITPOINTS)
		CheckStatLT(NearestEnemyOf(Myself),10,THAC0)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)

	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71440) // Spell: Greater Malison
		Spell(NearestEnemyOf(Myself),WIZARD_GREATER_MALISON)
END

/////////////////////////////////////////////////////////////////////////////////////// Debuff/Control Wands
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HasItem("wand02",Myself)
	NumCreatureVsPartyGT(Myself,4)

	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),2)
	!CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	!Race(NearestEnemyOf(Myself),DEMONIC)
	!Kit(NearestEnemyOf(Myself),CAVALIER)
	!Kit(NearestEnemyOf(Myself),Blackguard)
	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),2)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(SecondNearestEnemyOf(Myself),UNDEAD)
	!Race(SecondNearestEnemyOf(Myself),DEMONIC)
	!Kit(SecondNearestEnemyOf(Myself),CAVALIER)
	!Kit(SecondNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(SecondNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),2)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(ThirdNearestEnemyOf(Myself),UNDEAD)
	!Race(ThirdNearestEnemyOf(Myself),DEMONIC)
	!Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
	!Kit(ThirdNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(ThirdNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),2)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FourthNearestEnemyOf(Myself),UNDEAD)
	!Race(FourthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FourthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FourthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FourthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FifthNearestEnemyOf(Myself),2)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FifthNearestEnemyOf(Myself),UNDEAD)
	!Race(FifthNearestEnemyOf(Myself),DEMONIC)
	!Kit(FifthNearestEnemyOf(Myself),CAVALIER)
	!Kit(FifthNearestEnemyOf(Myself),Blackguard)
	CheckStatGT(FifthNearestEnemyOf(Myself),5,SAVEVSSPELL)
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71430) // Wand: Fear
		UseItem("wand02",NearestEnemyOf(Myself))
END

IF
  	ActionListEmpty()
	Class(Myself,MAGE_ALL)
	HasItem("wand08",Myself)
	NumCreatureVsPartyGT(Myself,4)

	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(NearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(NearestEnemyOf(Myself),1)
	!CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	!Race(NearestEnemyOf(Myself),DEMONIC)
	!Race(NearestEnemyOf(Myself),ELF)
	CheckStatLT(NearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(NearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(NearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(NearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(NearestEnemyOf(Myself),5)

	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(SecondNearestEnemyOf(Myself),1)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(SecondNearestEnemyOf(Myself),UNDEAD)
	!Race(SecondNearestEnemyOf(Myself),DEMONIC)
	!Race(SecondNearestEnemyOf(Myself),ELF)
	CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(SecondNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(SecondNearestEnemyOf(Myself),5)

	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(ThirdNearestEnemyOf(Myself),1)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(ThirdNearestEnemyOf(Myself),UNDEAD)
	!Race(ThirdNearestEnemyOf(Myself),DEMONIC)
	!Race(ThirdNearestEnemyOf(Myself),ELF)
	CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(ThirdNearestEnemyOf(Myself),5)

	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FourthNearestEnemyOf(Myself),1)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FourthNearestEnemyOf(Myself),UNDEAD)
	!Race(FourthNearestEnemyOf(Myself),DEMONIC)
	!Race(FourthNearestEnemyOf(Myself),ELF)
	CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FourthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FourthNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(FourthNearestEnemyOf(Myself),5)

	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(FifthNearestEnemyOf(Myself),1)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!General(FifthNearestEnemyOf(Myself),UNDEAD)
	!Race(FifthNearestEnemyOf(Myself),DEMONIC)
	!Race(FifthNearestEnemyOf(Myself),ELF)
	CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMAGIC)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BARBARIAN_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),BERSERKER_RAGE)
	!CheckSpellState(FifthNearestEnemyOf(Myself),MINSC_BERSERK)
	!CheckSpellState(FifthNearestEnemyOf(Myself),POTION_OF_CLARITY)
	LevelLT(FifthNearestEnemyOf(Myself),5)

	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)

	CheckStatGT(NearestEnemyOf(Myself),5,SAVEVSWANDS)

	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71435) // Wand: Sleep
		UseItem("wand08",NearestEnemyOf(Myself))
END

IF
  	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HasItem("wand04",Myself)
	!CheckSpellState(NearestEnemyOf(Myself),HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED | STATE_HELPLESS)
	CheckStatGT(NearestEnemyOf(Myself),10,SAVEVSWANDS)
	!General(NearestEnemyOf(Myself),UNDEAD)
	OR(4)
		CheckStatLT(NearestEnemyOf(Myself),5,SAVEVSSPELL)
		CheckStatLT(NearestEnemyOf(Myself),0,ARMORCLASS)
		CheckStatGT(NearestEnemyOf(Myself),75,MAXHITPOINTS)
		CheckStatLT(NearestEnemyOf(Myself),10,THAC0)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71432) // Wand: Paralyzation
		UseItem("wand04",NearestEnemyOf(Myself))
END

/////////////////////////////////////////////////////////////////////////////////////// Turn Undead
// Start turning undead if can turn nearby undead
IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(Nearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(Nearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(SecondNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(SecondNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(ThirdNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(ThirdNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(FourthNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(FourthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(FifthNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(FifthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(SixthNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(SixthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

IF
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range(SeventhNearest([EVILCUTOFF.UNDEAD]),12)
	CanTurn(SeventhNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71391) // Turn Undead
		Turn()
END

// Keep turning undead if already turning nearby undead
IF
	ActionListEmpty()
	ModalState(TURNUNDEAD)
	Range([EVILCUTOFF.UNDEAD],12)
	OR(7)
		CanTurn(Nearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SecondNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(ThirdNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(FourthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(FifthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SixthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SeventhNearest([EVILCUTOFF.UNDEAD]),5)
THEN
	RESPONSE #100
END

/////////////////////////////////////////////////////////////////////////////////////// Summon spells

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_AERIAL_SERVANT)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Aerial Servant
		Spell(Myself,CLERIC_AERIAL_SERVANT)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMATE_DEAD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71392) // Spell: Animate Undead
		Spell(Myself,CLERIC_ANIMATE_DEAD)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_ANIMATE_DEAD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71392) // Spell: Animate Undead
		Spell(Myself,WIZARD_ANIMATE_DEAD)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CALL_WOODLAND_BEINGS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71393) // Spell: Call Woodland Beings
		Spell(Myself,CLERIC_CALL_WOODLAND_BEINGS)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMAL_SUMMONING_3)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71394) // Spell: Animal Summoning 3
		Spell(Myself,CLERIC_ANIMAL_SUMMONING_3)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMAL_SUMMONING_2)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71395) // Spell: Animal Summoning 2
		Spell(Myself,CLERIC_ANIMAL_SUMMONING_2)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ANIMAL_SUMMONING_1)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71396) // Spell: Animal Summoning 1
		Spell(Myself,CLERIC_ANIMAL_SUMMONING_1)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CONJURE_ANIMALS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71481) // Spell: Conjure Animals
		Spell(Myself,CLERIC_CONJURE_ANIMALS)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CONJURE_FIRE_ELEMENTAL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71482) // Spell: Conjure Fire Elemental
		Spell(Myself,CLERIC_CONJURE_FIRE_ELEMENTAL)
END

////////////////////////////////////////////////////////////////////////////////// Scrolls: Summoning Spells

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL1L",Myself)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71503) // Spell: Monster Summoning 1
		UseItem("SCRL1L",Myself)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL2A",Myself)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71504) // Spell: Monster Summoning 2
		UseItem("SCRL2A",Myself)
END

IF
	ActionListEmpty()

	HotKey(Q)

	!HPGT(FifthNearestMyGroupOfType([ALLY.0.0.0.0.SUMMONED.0]),0)
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL2G",Myself)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71505) // Spell: Monster Summoning 3
		UseItem("SCRL2G",Myself)
END

////////////////////////////////////////////////////////////////////////////////// Buff Items

//IF
//	ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	Global("cloakGargoyle","GLOBAL",1)
//	HasItem("bdclck05",Myself) // Cloak Of The Gargoyle - Stone Form Once Per Day
//	//CheckStat(Myself,0,STONESKINS)
//	//CheckStat(Myself,0,STONESKINSGOLEM)
//	//!CheckSpellState(Myself,STONESKIN)
//THEN
//	RESPONSE #100
//      SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71483) // Item: Cloak Of The Gargoyle
//		SetGlobal("cloakGargoyle","GLOBAL",0)
//		UseItemSlotAbility(Myself,SLOT_CLOAK,1)
//END

// Cant figure out how to check we already used the item. It casts a spell that isn't in the spellstate list.
// Can we add the spellstate to the list compare to another spell with a spellstate in the list e.g. Bless

////////////////////////////////////////////////////////////////////////////////// If have a buff spell use it

// 1 Round = 6 Seconds Real Time
// 1 Turn = 10 Rounds = 1 Minute Real time
// 1 Hour = 5 Turns = 50 Rounds = 5 Minutes Real Time

// Level 5
// 600 rounds (1 Hour) - Self
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_IRONSKIN)
	!CheckSpellState(Myself,IRON_SKINS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71453) // Spell: Iron Skins
		Spell(Myself,CLERIC_IRONSKIN)
END

// Level 1
// 50 Rounds (5 minutes) - 15ft Radius
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71400) // Spell: Remove Fear
		Spell(Myself,CLERIC_REMOVE_FEAR)
END

// Level 4 - Necromancy 7
// 10 Rounds/Level (60 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DEATH_WARD)
	!CheckSpellState(PartySlot1,DEATH_WARD)
	!CheckStat(PartySlot1,1,DEATH_WARD)
	
	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,7,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,4)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71502) // Spell: Death Ward
		Spell(PartySlot1,CLERIC_DEATH_WARD)
END

// Level 4 - Abjuration 1
// 5 Rounds/Level (30 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)
	CheckStatLT(PartySlot1,99,RESISTELECTRICITY)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,4)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71469) // Spell: Protection From Lightning
		Spell(PartySlot1,CLERIC_PROTECTION_FROM_LIGHTNING)
END

// Level 4
// 4 Rounds/Level (24 seconds/Level) - 15ft Radius
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
	!CheckSpellState(Myself,PROTECTION_FROM_EVIL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71402) // Spell: Protection Group From Evil
		Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
END

// Level 5 - Enchantment 4
// 4 Rounds/Level (24 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(PartySlot1,0,CLERIC_CHAOTIC_COMMANDS)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,5)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71486) // Spell: Chaotic Commands
		Spell(PartySlot1,CLERIC_CHAOTIC_COMMANDS)
END

// Level 5 - Enchantment 4
// 4 Rounds/Level (24 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(PartySlot2,0,CLERIC_CHAOTIC_COMMANDS)

	!CheckStat(PartySlot2,1,MINORGLOBE)
	!CheckStat(PartySlot2,4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot2,5)
	!StateCheck(PartySlot2,STATE_INVISIBLE)
	!StateCheck(PartySlot2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot2,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,103300) // Spell: Chaotic Commands
		Spell(PartySlot2,CLERIC_CHAOTIC_COMMANDS)
END

// Level 5 - Enchantment 4
// 4 Rounds/Level (24 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(PartySlot3,0,CLERIC_CHAOTIC_COMMANDS)

	!CheckStat(PartySlot3,1,MINORGLOBE)
	!CheckStat(PartySlot3,4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot3,5)
	!StateCheck(PartySlot3,STATE_INVISIBLE)
	!StateCheck(PartySlot3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot3,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,103300) // Spell: Chaotic Commands
		Spell(PartySlot3,CLERIC_CHAOTIC_COMMANDS)
END

// Level 5 - Enchantment 4
// 4 Rounds/Level (24 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(PartySlot4,0,CLERIC_CHAOTIC_COMMANDS)

	!CheckStat(PartySlot4,1,MINORGLOBE)
	!CheckStat(PartySlot4,4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot4,5)
	!StateCheck(PartySlot4,STATE_INVISIBLE)
	!StateCheck(PartySlot4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot4,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,103300) // Spell: Chaotic Commands
		Spell(PartySlot4,CLERIC_CHAOTIC_COMMANDS)
END

// Level 5 - Enchantment 4
// 4 Rounds/Level (24 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(PartySlot5,0,CLERIC_CHAOTIC_COMMANDS)

	!CheckStat(PartySlot5,1,MINORGLOBE)
	!CheckStat(PartySlot5,4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot5,5)
	!StateCheck(PartySlot5,STATE_INVISIBLE)
	!StateCheck(PartySlot5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot5,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,103300) // Spell: Chaotic Commands
		Spell(PartySlot5,CLERIC_CHAOTIC_COMMANDS)
END

// Level 5 - Enchantment 4
// 4 Rounds/Level (24 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(PartySlot6,0,CLERIC_CHAOTIC_COMMANDS)

	!CheckStat(PartySlot6,1,MINORGLOBE)
	!CheckStat(PartySlot6,4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot6,5)
	!StateCheck(PartySlot6,STATE_INVISIBLE)
	!StateCheck(PartySlot6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot6,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,103300) // Spell: Chaotic Commands
		Spell(PartySlot6,CLERIC_CHAOTIC_COMMANDS)
END

// Level 1 - Abjuration 1
// 3 Rounds/Level (18 seconds/Level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot1,PROTECTION_FROM_EVIL)
	!CheckStatGT(PartySlot1,0,PROTECTION_FROM_EVIL)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,1)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot1,CLERIC_PROTECT_FROM_EVIL)
END

// Level 1
// 3 Rounds/Level (18 seconds/Level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot2,PROTECTION_FROM_EVIL)
	!CheckStatGT(PartySlot2,0,PROTECTION_FROM_EVIL)

	!CheckStat(PartySlot2,1,MINORGLOBE)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot2,1)
	!StateCheck(PartySlot2,STATE_INVISIBLE)
	!StateCheck(PartySlot2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot2,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot2,CLERIC_PROTECT_FROM_EVIL)
END

// Level 1
// 3 Rounds/Level (18 seconds/Level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot3,PROTECTION_FROM_EVIL)
	!CheckStatGT(PartySlot3,0,PROTECTION_FROM_EVIL)

	!CheckStat(PartySlot3,1,MINORGLOBE)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot3,1)
	!StateCheck(PartySlot3,STATE_INVISIBLE)
	!StateCheck(PartySlot3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot3,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot3,CLERIC_PROTECT_FROM_EVIL)
END

// Level 1
// 3 Rounds/Level (18 seconds/Level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot4,PROTECTION_FROM_EVIL)
	!CheckStatGT(PartySlot4,0,PROTECTION_FROM_EVIL)

	!CheckStat(PartySlot4,1,MINORGLOBE)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot4,1)
	!StateCheck(PartySlot4,STATE_INVISIBLE)
	!StateCheck(PartySlot4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot4,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot4,CLERIC_PROTECT_FROM_EVIL)
END

// Level 1
// 3 Rounds/Level (18 seconds/Level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot5,PROTECTION_FROM_EVIL)
	!CheckStatGT(PartySlot5,0,PROTECTION_FROM_EVIL)

	!CheckStat(PartySlot5,1,MINORGLOBE)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot5,1)
	!StateCheck(PartySlot5,STATE_INVISIBLE)
	!StateCheck(PartySlot5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot5,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot5,CLERIC_PROTECT_FROM_EVIL)
END

// Level 1
// 3 Rounds/Level (18 seconds/Level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)
	!CheckSpellState(PartySlot6,PROTECTION_FROM_EVIL)
	!CheckStatGT(PartySlot6,0,PROTECTION_FROM_EVIL)

	!CheckStat(PartySlot6,1,MINORGLOBE)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot6,1)
	!StateCheck(PartySlot6,STATE_INVISIBLE)
	!StateCheck(PartySlot6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot6,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71401) // Spell: Protection From Evil
		Spell(PartySlot6,CLERIC_PROTECT_FROM_EVIL)
END

// Level 5 - Alteration 8
// 3 Rounds/Level (18 seconds/level) - 1 Creature
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHAMPIONS_STRENGTH)
	CheckStatLT(WeakestOf(Myself),18,STRENGTH_MODIFIER)

	!CheckStat(WeakestOf(Myself),1,MINORGLOBE)
	!CheckStat(WeakestOf(Myself),8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(WeakestOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(WeakestOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(WeakestOf(Myself),5)
	!StateCheck(WeakestOf(Myself),STATE_INVISIBLE)
	!StateCheck(WeakestOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(WeakestOf(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71456) // Spell: Champions Strength
		Spell(WeakestOf(Myself),CLERIC_CHAMPIONS_STRENGTH)
END

// Level 4 - Abjuration 1
// 10 Rounds + 1 Round/Level (60 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	CheckStat(PartySlot1,0,CLERIC_FREE_ACTION)
	!CheckSpellState(PartySlot1,FREE_ACTION)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,4)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Free Action
		Spell(PartySlot1,CLERIC_FREE_ACTION)
END

// Level 4 - Abjuration 1
// 10 Rounds + 1 Round/Level (60 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	CheckStat(PartySlot2,0,CLERIC_FREE_ACTION)
	!CheckSpellState(PartySlot2,FREE_ACTION)

	!CheckStat(PartySlot2,1,MINORGLOBE)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot2,4)
	!StateCheck(PartySlot2,STATE_INVISIBLE)
	!StateCheck(PartySlot2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot2,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Free Action
		Spell(PartySlot2,CLERIC_FREE_ACTION)
END

// Level 4 - Abjuration 1
// 10 Rounds + 1 Round/Level (60 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	CheckStat(PartySlot3,0,CLERIC_FREE_ACTION)
	!CheckSpellState(PartySlot3,FREE_ACTION)

	!CheckStat(PartySlot3,1,MINORGLOBE)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot3,4)
	!StateCheck(PartySlot3,STATE_INVISIBLE)
	!StateCheck(PartySlot3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot3,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Free Action
		Spell(PartySlot3,CLERIC_FREE_ACTION)
END

// Level 4 - Abjuration 1
// 10 Rounds + 1 Round/Level (60 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	CheckStat(PartySlot4,0,CLERIC_FREE_ACTION)
	!CheckSpellState(PartySlot4,FREE_ACTION)

	!CheckStat(PartySlot4,1,MINORGLOBE)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot4,4)
	!StateCheck(PartySlot4,STATE_INVISIBLE)
	!StateCheck(PartySlot4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot4,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Free Action
		Spell(PartySlot4,CLERIC_FREE_ACTION)
END

// Level 4 - Abjuration 1
// 10 Rounds + 1 Round/Level (60 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	CheckStat(PartySlot5,0,CLERIC_FREE_ACTION)
	!CheckSpellState(PartySlot5,FREE_ACTION)

	!CheckStat(PartySlot5,1,MINORGLOBE)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot5,4)
	!StateCheck(PartySlot5,STATE_INVISIBLE)
	!StateCheck(PartySlot5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot5,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Free Action
		Spell(PartySlot5,CLERIC_FREE_ACTION)
END

// Level 4 - Abjuration 1
// 10 Rounds + 1 Round/Level (60 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	CheckStat(PartySlot6,0,CLERIC_FREE_ACTION)
	!CheckSpellState(PartySlot6,FREE_ACTION)

	!CheckStat(PartySlot6,1,MINORGLOBE)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot6,4)
	!StateCheck(PartySlot6,STATE_INVISIBLE)
	!StateCheck(PartySlot6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot6,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,?) // Spell: Free Action
		Spell(PartySlot6,CLERIC_FREE_ACTION)
END

// Level 2 - Alteration 8
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot1,BARKSKIN)

	!Heard([ANYONE],CASTING_BARKSKIN) // If someone else casting barkskin

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,2)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71403) // Spell: Barkskin
		Shout(CASTING_BARKSKIN) // Casting Barksin
		Spell(PartySlot1,CLERIC_BARKSKIN)
END

// Level 2 - Alteration 8
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot2,BARKSKIN)

	!Heard([ANYONE],CASTING_BARKSKIN) // If someone else casting barkskin

	!CheckStat(PartySlot2,1,MINORGLOBE)
	!CheckStat(PartySlot2,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot2,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot2,2)
	!StateCheck(PartySlot2,STATE_INVISIBLE)
	!StateCheck(PartySlot2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot2,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71403) // Spell: Barkskin
		Shout(CASTING_BARKSKIN) // Casting Barksin
		Spell(PartySlot2,CLERIC_BARKSKIN)
END

// Level 2 - Alteration 8
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot3,BARKSKIN)

	!Heard([ANYONE],CASTING_BARKSKIN) // If someone else casting barkskin

	!CheckStat(PartySlot3,1,MINORGLOBE)
	!CheckStat(PartySlot3,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot3,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot3,2)
	!StateCheck(PartySlot3,STATE_INVISIBLE)
	!StateCheck(PartySlot3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot3,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71403) // Spell: Barkskin
		Shout(CASTING_BARKSKIN) // Casting Barksin
		Spell(PartySlot3,CLERIC_BARKSKIN)
END

// Level 2 - Alteration 8
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot4,BARKSKIN)

	!Heard([ANYONE],CASTING_BARKSKIN) // If someone else casting barkskin

	!CheckStat(PartySlot4,1,MINORGLOBE)
	!CheckStat(PartySlot4,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot4,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot4,2)
	!StateCheck(PartySlot4,STATE_INVISIBLE)
	!StateCheck(PartySlot4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot4,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71403) // Spell: Barkskin
		Shout(CASTING_BARKSKIN) // Casting Barksin
		Spell(PartySlot4,CLERIC_BARKSKIN)
END

// Level 2 - Alteration 8
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot5,BARKSKIN)

	!Heard([ANYONE],CASTING_BARKSKIN) // If someone else casting barkskin

	!CheckStat(PartySlot5,1,MINORGLOBE)
	!CheckStat(PartySlot5,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot5,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot5,2)
	!StateCheck(PartySlot5,STATE_INVISIBLE)
	!StateCheck(PartySlot5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot5,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71403) // Spell: Barkskin
		Shout(CASTING_BARKSKIN) // Casting Barksin
		Spell(PartySlot5,CLERIC_BARKSKIN)
END

// Level 2 - Alteration 8
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)
	!CheckSpellState(PartySlot6,BARKSKIN)

	!Heard([ANYONE],CASTING_BARKSKIN) // If someone else casting barkskin

	!CheckStat(PartySlot6,1,MINORGLOBE)
	!CheckStat(PartySlot6,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot6,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot6,2)
	!StateCheck(PartySlot6,STATE_INVISIBLE)
	!StateCheck(PartySlot6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot6,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71403) // Spell: Barkskin
		Shout(CASTING_BARKSKIN) // Casting Barksin
		Spell(PartySlot6,CLERIC_BARKSKIN)
END

// Level 1
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_SHILLELAGH)  // SPPR110.SPL (Shillelagh)
	!HasItem("FBLADE",Myself)  // Flame Blade
	!HasItem("SHILLE",Myself)  // Shillelagh
	!HasItem("SHAMMR",Myself)  // Spiritual Hammer
	!HasItem("CHILLT",Myself)  // Chill Touch
	!HasItem("GHOULT",Myself)  // Ghoul Touch
	!HasItem("SGRASP",Myself)  // Shocking Grasp

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71407) // Spell: Shillelagh
		Spell(Myself,CLERIC_SHILLELAGH)  // SPPR110.SPL (Shillelagh)
END

// Level 2
// 4 Rounds + 1 Round/Level (24 seconds + 6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_FLAME_BLADE)
	!HasItem("FBLADE",Myself)  // Flame Blade
	!HasItem("SHILLE",Myself)  // Shillelagh
	!HasItem("SHAMMR",Myself)  // Spiritual Hammer
	!HasItem("CHILLT",Myself)  // Chill Touch
	!HasItem("GHOULT",Myself)  // Ghoul Touch
	!HasItem("SGRASP",Myself)  // Shocking Grasp

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71408) // Spell: Flame Blade
		Spell(Myself,CLERIC_FLAME_BLADE)
END

// Level 1
// 3 Rounds + 1 Round/Level (18 seconds + 6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH)
	!CheckSpellState(Myself,ARMOR_OF_FAITH)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71410) // Spell: Armor Of Faith
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)
END

// Level 3 - Abjuration 1
// 3 Rounds + 1 Round/Level (18 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_FIRE)
	CheckStatLT(PartySlot1,99,RESISTFIRE)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,3)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71480) // Spell: Protection From Fire
		Spell(PartySlot1,CLERIC_PROTECTION_FROM_FIRE)
END

// Level 5 - Alteration 8
// 3 Rounds + 1 Round/Level (18 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_MAGIC_RESISTANCE)
	CheckStatLT(PartySlot1,99,RESISTMAGIC)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,5)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71470) // Spell: Magic Resistance
		Spell(PartySlot1,CLERIC_MAGIC_RESISTANCE)
END

// Level 2 - Necromancy 2, Conjuration 7
// 1 Round + 1 Round/Level (6 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_AID)
	!CheckSpellState(PartySlot1,AID)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,7,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,2)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71404) // Spell: Aid
		Spell(PartySlot1,CLERIC_AID)
END

// Level 5
// 1 Round/Level (6 seconds/level) - Self
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71464) // Spell: Righteous Magic
		Spell(WeakestOf(Myself),CLERIC_RIGHTEOUS_MAGIC)
END

// Note: There is no resist fire or resist cold spell for clerics but a single resist fire and cold spell
// Casting CLERIC_RESIST_FIRE or CLERIC_RESIST_COLD actually casts the resist fire and cold spell
// Level 2 - Alteration 8
// 1 Round/Level (6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_RESIST_FIRE)
	OR(2)
		CheckStatLT(PartySlot1,99,RESISTFIRE)
		CheckStatLT(PartySlot1,99,RESISTCOLD)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,2)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71471) // Spell: Resist Fire And Cold
		Spell(PartySlot1,CLERIC_RESIST_FIRE)
END

// Level 4
// 1 Rounds/Level (6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLY_POWER)
	!CheckSpellState(Myself,HOLY_POWER)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71411) // Spell: Holy Power
		Spell(Myself,CLERIC_HOLY_POWER)
END

// Level 3
// 10 Rounds (60 seconds) - 15ft Radius
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_STRENGTH_OF_ONE)
	CheckStatLT(WeakestOf(Myself),18,STRENGTH_MODIFIER)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71454) // Spell: Strength Of One
		Spell(WeakestOf(Myself),CLERIC_STRENGTH_OF_ONE)
END

// Level 2 - Conjuration 2
// 10 Rounds (60 seconds) - 15ft Radius
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Chant)
	!StateCheck(PartySlot1,STATE_CHANT)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,2)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71398) // Spell: Chant
		Spell(PartySlot1,CLERIC_CHANT)  // SPPR203.SPL (Chant)
END

// 10 Rounds (60 seconds) - Self
//IF
//	ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	HaveSpell(INNATE_DRAW_UPON_HOLY_MIGHT)
//	!CheckSpellState(Myself,DRAW_UPON_HOLY_MIGHT)
//	!StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		////DisplayStringHead(Myself,71409) // Spell: Holy Might
//		Spell(Myself,INNATE_DRAW_UPON_HOLY_MIGHT)
//END

// Level 1 - Conjuration 2
// 6 Rounds (36 seconds) - 15ft Radius
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_BLESS)  // SPPR101.SPL (Bless)
	!StateCheck(PartySlot1,STATE_BLESS)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,1)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71397) // Spell: Bless
		Spell(PartySlot1,CLERIC_BLESS)  // SPPR101.SPL (Bless)
END

// Level 4
// 6 Rounds (36 seconds) - 15ft Radius
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DEFENSIVE_HARMONY)
	!CheckStat(Myself,1,CLERIC_DEFENSIVE_HARMONY)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71399) // Spell: Defensive Harmony
		Spell(Myself,CLERIC_DEFENSIVE_HARMONY)
END

// Level 2
// 4 Rounds (24 seconds) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
	!CheckSpellState(Myself,DRAW_UPON_HOLY_MIGHT)
	!StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71409) // Spell: Holy Might
		Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)
END

// Level 7
// 2 hours (10 minutes) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_IMPROVED_CHAOS_SHIELD)
	!CheckSpellState(Myself,IMPROVED_CHAOS_SHIELD)
	!CheckSpellState(Myself,CHAOS_SHIELD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,103284) // Spell: Chaos Shield
		Spell(Myself,WIZARD_IMPROVED_CHAOS_SHIELD)
END

// Level 2
// 5 Rounds + 10 Rounds/5 Levels (30 seconds + 60 seconds/5 levels) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_CHAOS_SHIELD)
	!CheckSpellState(Myself,IMPROVED_CHAOS_SHIELD)
	!CheckSpellState(Myself,CHAOS_SHIELD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71405) // Spell: Chaos Shield
		Spell(Myself,WIZARD_CHAOS_SHIELD)
END

// Level 3
// Until Charges Depleted - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)
	!HasItem("MELFMET",Myself)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71445) // Spell: Melfs Minute Meteors
		Spell(Myself,WIZARD_MELF_METEOR)
END

// Level 4
// 600 Rounds (1 Hour) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_STONE_SKIN)
	!CheckSpellState(Myself,STONESKIN)
	!CheckStatGT(Myself,0,STONESKINS)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71484) // Spell: Stoneskin
		Spell(Myself,WIZARD_STONE_SKIN)
END

// Level 2 - Alteration 8
// 10 Rounds/Level (60 seconds/level) - 1 Creature
IF
	ActionListEmpty()
	!GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_STRENGTH)
	CheckStatLT(WeakestOf(Myself),18,STRENGTH_MODIFIER)

	!CheckStat(WeakestOf(Myself),1,MINORGLOBE)
	!CheckStat(WeakestOf(Myself),8,WIZARD_SPELL_IMMUNITY)
	!CheckStat(WeakestOf(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(WeakestOf(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(WeakestOf(Myself),2)
	!StateCheck(WeakestOf(Myself),STATE_INVISIBLE)
	!StateCheck(WeakestOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(WeakestOf(Myself),STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
	    SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71455) // Spell: Strength
		Spell(WeakestOf(Myself),WIZARD_STRENGTH)
END

// Level 5 - Abjuration 1
// 10 Rounds/Level (60 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_PROTECTION_FROM_ACID)
	CheckStatLT(PartySlot1,99,RESISTACID)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,5)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71478) // Spell: Protection From Acid
		Spell(PartySlot1,WIZARD_PROTECTION_FROM_ACID)
END

// Level 3 - Abjuration 1
// 10 Rounds/Level (60 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_PROTECTION_FROM_FIRE)
	CheckStatLT(PartySlot1,99,RESISTFIRE)

	!CheckStat(PartySlot1,1,MINORGLOBE)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_IMMUNITY)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStat(PartySlot1,1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(PartySlot1,3)
	!StateCheck(PartySlot1,STATE_INVISIBLE)
	!StateCheck(PartySlot1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(PartySlot1,STATE_NOT_TARGETABLE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71480) // Spell: Protection From Fire
		Spell(PartySlot1,WIZARD_PROTECTION_FROM_FIRE)
END

// Level 1
// 50 rounds (5 minutes) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_SHIELD)
	!CheckSpellState(Myself,WIZARD_SHIELD)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71406) // Spell: Shield
		Spell(Myself,WIZARD_SHIELD)
END

// Level 2
// 50 Rounds (5 minutes) - 15ft Radius
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_RESIST_FEAR)
	!CheckSpellState(Myself,RESIST_FEAR)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71412) // Spell: Resist Fear
		Spell(Myself,WIZARD_RESIST_FEAR)
END

// Level 2
// 3 Rounds + 1 Rounds/Level (18 seconds + 6 seconds/level) - Self
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MIRROR_IMAGE)
	!StateCheck(Myself,STATE_MIRRORIMAGE)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71414) // Spell: Mirror Image
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

// Level 4
// 3 Rounds + 1 Rounds/Level (18 seconds + 6 seconds/level) - 1 Creature
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71417) // Spell: Improved Invisibility
		Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

//////////////////////////////////////////////////////////////////////////// Decide On Next Target You Can See
// Protect The Wizard if their attacker is not disabled
IF
	ActionListEmpty()

	HPPercentGT(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),0)
	!InParty(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])))

	!CheckSpellState(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),HOPELESSNESS)
	!CheckSpellState(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),HELD)
	!CheckSpellState(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),ENTANGLE)
	!CheckSpellState(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),WEB)
	!StateCheck(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),STATE_CHARMED)
	!StateCheck(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),STATE_CONFUSED)
	!StateCheck(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),STATE_SLEEPING)
	!StateCheck(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),STATE_DISABLED)
	!StateCheck(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),STATE_PANIC)
	!StateCheck(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])),STATE_NOT_TARGETABLE)

	See(LastAttackerOf(NearestMyGroupOfType([ALLY.0.0.MAGE_ALL.0.0.0])))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71443) // Helping Wizard
		Continue()
END

// Help hurt allies if their attacker is not disabled
IF
	ActionListEmpty()

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	HPPercentLT(MostDamagedOf(Myself),80)
	HPPercentGT(LastAttackerOf(MostDamagedOf(Myself)),0)

	!CheckSpellState(LastAttackerOf(MostDamagedOf(Myself)),HOPELESSNESS)
	!CheckSpellState(LastAttackerOf(MostDamagedOf(Myself)),HELD)
	!CheckSpellState(LastAttackerOf(MostDamagedOf(Myself)),ENTANGLE)
	!CheckSpellState(LastAttackerOf(MostDamagedOf(Myself)),WEB)
	!StateCheck(LastAttackerOf(MostDamagedOf(Myself)),STATE_CHARMED)
	!StateCheck(LastAttackerOf(MostDamagedOf(Myself)),STATE_CONFUSED)
	!StateCheck(LastAttackerOf(MostDamagedOf(Myself)),STATE_SLEEPING)
	!StateCheck(LastAttackerOf(MostDamagedOf(Myself)),STATE_DISABLED)
	!StateCheck(LastAttackerOf(MostDamagedOf(Myself)),STATE_PANIC)
	!StateCheck(LastAttackerOf(MostDamagedOf(Myself)),STATE_NOT_TARGETABLE)

	See(LastAttackerOf(MostDamagedOf(Myself)))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71424) // Helping Allies
		Continue()
END

// Attack Enemy Spellcasters if they are not disabled
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)

	!CheckSpellState(NearestEnemyOfType([0.0.0.MAGE_ALL]),HOPELESSNESS)
	!CheckSpellState(NearestEnemyOfType([0.0.0.MAGE_ALL]),HELD)
	!CheckSpellState(NearestEnemyOfType([0.0.0.MAGE_ALL]),ENTANGLE)
	!CheckSpellState(NearestEnemyOfType([0.0.0.MAGE_ALL]),WEB)
	!StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_CHARMED)
	!StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_CONFUSED)
	!StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_SLEEPING)
	!StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_DISABLED)
	!StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_PANIC)
	!StateCheck(NearestEnemyOfType([0.0.0.MAGE_ALL]),STATE_NOT_TARGETABLE)

	See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))

	HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)

	!CheckSpellState(NearestEnemyOfType([0.0.0.CLERIC_ALL]),HOPELESSNESS)
	!CheckSpellState(NearestEnemyOfType([0.0.0.CLERIC_ALL]),HELD)
	!CheckSpellState(NearestEnemyOfType([0.0.0.CLERIC_ALL]),ENTANGLE)
	!CheckSpellState(NearestEnemyOfType([0.0.0.CLERIC_ALL]),WEB)
	!StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_CHARMED)
	!StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_CONFUSED)
	!StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_SLEEPING)
	!StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_DISABLED)
	!StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_PANIC)
	!StateCheck(NearestEnemyOfType([0.0.0.CLERIC_ALL]),STATE_NOT_TARGETABLE)

	See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))

	HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)

	!CheckSpellState(NearestEnemyOfType([0.0.0.DRUID_ALL]),HOPELESSNESS)
	!CheckSpellState(NearestEnemyOfType([0.0.0.DRUID_ALL]),HELD)
	!CheckSpellState(NearestEnemyOfType([0.0.0.DRUID_ALL]),ENTANGLE)
	!CheckSpellState(NearestEnemyOfType([0.0.0.DRUID_ALL]),WEB)
	!StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_CHARMED)
	!StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_CONFUSED)
	!StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_SLEEPING)
	!StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_DISABLED)
	!StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_PANIC)
	!StateCheck(NearestEnemyOfType([0.0.0.DRUID_ALL]),STATE_NOT_TARGETABLE)

	See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))

	HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)

	!CheckSpellState(NearestEnemyOfType([0.0.0.BARD_ALL]),HOPELESSNESS)
	!CheckSpellState(NearestEnemyOfType([0.0.0.BARD_ALL]),HELD)
	!CheckSpellState(NearestEnemyOfType([0.0.0.BARD_ALL]),ENTANGLE)
	!CheckSpellState(NearestEnemyOfType([0.0.0.BARD_ALL]),WEB)
	!StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_CHARMED)
	!StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_CONFUSED)
	!StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_SLEEPING)
	!StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_DISABLED)
	!StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_PANIC)
	!StateCheck(NearestEnemyOfType([0.0.0.BARD_ALL]),STATE_NOT_TARGETABLE)

	See(NearestEnemyOfType([0.0.0.BARD_ALL]))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71444) // Attacking Spellcasters
		Continue()
END

// If attacked by an enemy attack them if they are not disabled
IF 
	ActionListEmpty()

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]),0)
		!See(LastAttackerOf([ALLY.0.0.MAGE_ALL.0.0.0]))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	AttackedBy([ENEMY],DEFAULT)
	!InParty(LastAttackerOf(Myself))
	
	!CheckSpellState(LastAttackerOf(Myself),HOPELESSNESS)
	!CheckSpellState(LastAttackerOf(Myself),HELD)
	!CheckSpellState(LastAttackerOf(Myself),ENTANGLE)
	!CheckSpellState(LastAttackerOf(Myself),WEB)
	!StateCheck(LastAttackerOf(Myself),STATE_CHARMED)
	!StateCheck(LastAttackerOf(Myself),STATE_CONFUSED)
	!StateCheck(LastAttackerOf(Myself),STATE_SLEEPING)
	!StateCheck(LastAttackerOf(Myself),STATE_DISABLED)
	!StateCheck(LastAttackerOf(Myself),STATE_PANIC)
	!StateCheck(LastAttackerOf(Myself),STATE_NOT_TARGETABLE)

	See(LastAttackerOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71425) // Attacking My Attacker
		Continue()
END

// Attack weakest enemy that is not disabled
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	HPPercentLT(NearestEnemyOf(Myself),50)

	!CheckSpellState(NearestEnemyOf(Myself),HOPELESSNESS)
	!CheckSpellState(NearestEnemyOf(Myself),HELD)
	!CheckSpellState(NearestEnemyOf(Myself),ENTANGLE)
	!CheckSpellState(NearestEnemyOf(Myself),WEB)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71426) // Attacking Weakest Enemy
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)

	HPPercentLT(SecondNearestEnemyOf(Myself),50)

	!CheckSpellState(SecondNearestEnemyOf(Myself),HOPELESSNESS)
	!CheckSpellState(SecondNearestEnemyOf(Myself),HELD)
	!CheckSpellState(SecondNearestEnemyOf(Myself),ENTANGLE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),WEB)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71426) // Attacking Weakest Enemy
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)

	HPPercentLT(ThirdNearestEnemyOf(Myself),50)
	
	!CheckSpellState(ThirdNearestEnemyOf(Myself),HOPELESSNESS)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),HELD)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),ENTANGLE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),WEB)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71426) // Attacking Weakest Enemy
		Continue()
END

// Attack nearby enemies you can see that are not disabled
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)
	!HPPercentLT(ThirdNearestEnemyOf(Myself),50)

	!CheckSpellState(NearestEnemyOf(Myself),HOPELESSNESS)
	!CheckSpellState(NearestEnemyOf(Myself),HELD)
	!CheckSpellState(NearestEnemyOf(Myself),ENTANGLE)
	!CheckSpellState(NearestEnemyOf(Myself),WEB)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71427) // Attacking Nearby Enemies
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)
	!HPPercentLT(ThirdNearestEnemyOf(Myself),50)

	!CheckSpellState(SecondNearestEnemyOf(Myself),HOPELESSNESS)
	!CheckSpellState(SecondNearestEnemyOf(Myself),HELD)
	!CheckSpellState(SecondNearestEnemyOf(Myself),ENTANGLE)
	!CheckSpellState(SecondNearestEnemyOf(Myself),WEB)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71427) // Attacking Nearby Enemies
		Continue()
END

IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)
	!HPPercentLT(ThirdNearestEnemyOf(Myself),50)

	!CheckSpellState(ThirdNearestEnemyOf(Myself),HOPELESSNESS)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),HELD)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),ENTANGLE)
	!CheckSpellState(ThirdNearestEnemyOf(Myself),WEB)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)

	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71427) // Attacking Nearby Enemies
		Continue()
END

// Attack nearby enemies you can see
IF
	ActionListEmpty()

	// Skip if helping hurt allies
	OR(2)
		!HPPercentLT(MostDamagedOf(Myself),80)
		!See(LastAttackerOf(MostDamagedOf(Myself)))

	// Skip if protecting wizard
	OR(2)
		!HPPercentGT(LastAttackerOf(PartySlot1),0)
		!See(LastAttackerOf(PartySlot1))

	// Skip if attacking spellcaster
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.MAGE_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.CLERIC_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.DRUID_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	OR(2)
		!HPPercentGT(NearestEnemyOfType([0.0.0.BARD_ALL]),0)
		!See(NearestEnemyOfType([0.0.0.BARD_ALL]))

	// Skip if attacking my attacker
	!AttackedBy([ENEMY],DEFAULT)

	// Skip if attacking weakest enemy
	!HPPercentLT(NearestEnemyOf(Myself),50)
	!HPPercentLT(SecondNearestEnemyOf(Myself),50)
	!HPPercentLT(ThirdNearestEnemyOf(Myself),50)

	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71427) // Attacking Nearby Enemies
		Continue()
END

////////////////////////////////////////////////////////////////////////////////////// Offensive Spells On Target You Can See

// Level 3 - Evocation
IF
	Class(Myself,MAGE_ALL)
	HaveSpell(WIZARD_FIREBALL)
	!Range(FarthestEnemyOf(Myself),17)
	!StateCheck(FarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	TriggerOverride(FarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
	!TriggerOverride(FarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
	See(FarthestEnemyOf(Myself)) // Target the fireball target
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		SetGlobalTimer("castingfireball","LOCALS",6) // Starting fireball
		//DisplayStringHead(Myself,71418) // Spell: Fireball
		Spell(FarthestEnemyOf(Myself),WIZARD_FIREBALL)
END

// Level 1 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MAGIC_MISSILE)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
	!ImmuneToSpellLevel(LastSeenBy(Myself),1)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71419) // Spell: Magic Missile
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Level 1 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_CHROMATIC_ORB)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(LastSeenBy(Myself),1)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71479) // Spell: Chromatic Orb
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

// Level 3 - Conjuration
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING) 
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	CheckStatGT(LastSeenBy(Myself),5,SAVEVSSPELL)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71420) // Spell: Flame Arrow
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

// Level 2 - Conjuration
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING) 
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTACID)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71421) // Spell: Melf Acid Arrow
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Level 2 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71422) // Spell: Agannazar Scorcher
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

// Level 3 - Necromancy
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HaveSpell(CLERIC_HOLY_SMITE)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY) 
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!ImmuneToSpellLevel(LastSeenBy(Myself),3)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71423) // Spell: Holy Smite
		Spell(LastSeenBy(Myself),CLERIC_HOLY_SMITE)
END

//////////////////////////////////////////////////////////////////// Offensive Wands On Targets You Can See
IF
    ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand06",Myself)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSWANDS)
	OR(4)
		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
		CheckStatLT(LastSeenBy(Myself),10,THAC0)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71434) // Wand: Frost
		UseItem("wand06",LastSeenBy(Myself))
END

IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,MAGE_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand03",Myself)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSWANDS)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71431) // Wand: Magic Missile
		UseItem("wand03",LastSeenBy(Myself))
END

IF
  	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	Class(Myself,CLERIC_ALL)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HasItem("wand11",Myself)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSWANDS)
	OR(4)
		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
		CheckStatLT(LastSeenBy(Myself),10,THAC0)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		//DisplayStringHead(Myself,71437) // Wand: Heavens
		UseItem("wand11",LastSeenBy(Myself))
END

IF
	Class(Myself,MAGE_ALL)
	HasItem("wand05",Myself)
	!Range(FarthestEnemyOf(Myself),17)
	!StateCheck(FarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	TriggerOverride(FarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
	!TriggerOverride(FarthestEnemyOf(Myself),Range(NearestEnemyOf(Myself),22))
	See(FarthestEnemyOf(Myself)) // Target the fireball target
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		SetGlobalTimer("castingfireball","LOCALS",6) // Starting fireball
		//DisplayStringHead(Myself,71433) // Wand: Fire
		XEquipItem("wand05",Myself,SLOT_MISC0,EQUIP)
		UseItemSlotAbility(FarthestEnemyOf(Myself),SLOT_MISC0,0)
END

//IF
//	Class(Myself,MAGE_ALL)
//	HasItem("wand05",Myself)
	//!InLine(LastSeenBy(Myself),PartySlot1)
	//!InLine(LastSeenBy(Myself),PartySlot2)
	//!InLine(LastSeenBy(Myself),PartySlot3)
	//!InLine(LastSeenBy(Myself),PartySlot4)
	//!InLine(LastSeenBy(Myself),PartySlot5)
	//!InLine(LastSeenBy(Myself),PartySlot6)

//	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
//	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY) 
//	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
//	!ImmuneToSpellLevel(LastSeenBy(Myself),2)

//	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
//	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
//	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

//	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
//	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

//	OR(4)
//		CheckStatLT(LastSeenBy(Myself),5,SAVEVSSPELL)
//		CheckStatLT(LastSeenBy(Myself),0,ARMORCLASS)
//		CheckStatGT(LastSeenBy(Myself),75,MAXHITPOINTS)
//		CheckStatLT(LastSeenBy(Myself),10,THAC0)
//	!InParty(LastSeenBy(Myself))
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71433) // Wand: Fire
//		XEquipItem("wand05",Myself,SLOT_MISC0,EQUIP)
//		UseItemSlotAbility(LastSeenBy(Myself),SLOT_MISC0,1)
//END

//IF
//  ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	Class(Myself,MAGE_ALL)
//	HasItem("wand10",Myself)
//	See(NearestEnemyOf(Myself))
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71436) // Wand: Monster Summoning
//		UseItem("wand10",LastSeenBy(Myself))
//END

//IF
//  ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	Class(Myself,MAGE_ALL)
//	HasItem("wand18",Myself)
//	See(NearestEnemyOf(Myself))
//THEN
//	RESPONSE #100
//        SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71438) // Wand: Spell Striking
//		UseItem("wand18",LastSeenBy(Myself))
//END

//////////////////////////////////////////////////////////////////// Scrolls: Offensive Spells

// Level 1 - Evocation
IF
	ActionListEmpty()
    !GlobalTimerNotExpired("castnattack","LOCALS")
	HasItem("SCRL77",Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)

	!CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
	!ImmuneToSpellLevel(LastSeenBy(Myself),1)

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)

	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
        SetGlobalTimer("castnattack","LOCALS",6)
		////DisplayStringHead(Myself,71419) // Spell: Magic Missile
		UseItem("SCRL77",Myself)
END

//////////////////////////////////////////////////////////////////// Change Melee Weapon If Not Effective

//IF
//	ActionListEmpty()
//	//!GlobalTimerNotExpired("checkweapon0","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!CheckWeaponCanDamageV2(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		//DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON0,0)
//		//SetGlobalTimer("checkweapon0","LOCALS",20)
//END

//IF
//	ActionListEmpty()
//	//!GlobalTimerNotExpired("checkweapon1","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!WeaponCanDamage(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		//DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON1,0)
//		//SetGlobalTimer("checkweapon1","LOCALS",20)
//END

//IF
//	ActionListEmpty()
//	!GlobalTimerNotExpired("checkweapon2","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!WeaponCanDamage(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		//DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON2,0)
//		SetGlobalTimer("checkweapon2","LOCALS",20)
//END

//IF
//	ActionListEmpty()
//	!GlobalTimerNotExpired("checkweapon3","LOCALS")
//	!IsWeaponRanged(Myself)
//	HPPercentGT(LastSeenBy(Myself),0)
//	!WeaponCanDamage(LastSeenBy(Myself),BOTH)
//THEN
//	RESPONSE #100
//		//DisplayStringHead(Myself,71441) // Changing Weapon
//		SelectWeaponAbility(SLOT_WEAPON3,0)
//		SetGlobalTimer("checkweapon3","LOCALS",20)
//END

/////////////////////////////////////////////////////////// Equip Arrows If Out Of Ammo

//IF
//	!HasItemEquiped("AROW01",Myself)
//THEN
//	RESPONSE #100
///		//DisplayStringHead(Myself,10)
//END

IF
	!HasItemEquiped("AROW01",Myself) // passing for both
	HasItemCategory(Myself,BOW,FALSE) // passing for both when false, neither when true
	HasItem("AROW01",Myself) // Arrow
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71467) // Equipping Arrows
		XEquipItem("AROW01",Myself,SLOT_AMMO0,EQUIP)
		Continue()
END

//	HasItem("AROW02",Myself) // Arrow + 1
//	HasItem("AROW03",Myself) // Arrow Of Slaying
//	HasItem("AROW04",Myself) // Acid Arrow + 1
//	HasItem("AROW05",Myself) // Arrow Of Biting
//	HasItem("AROW06",Myself) // Arrow Of Detonation
//	HasItem("AROW07",Myself) // Arrow Of Dispelling
//	HasItem("AROW08",Myself) // Arrow Of Fire + 2
//	HasItem("AROW09",Myself) // Arrow Of Ice
//	HasItem("AROW10",Myself) // Arrow Of Piercing + 1
//	HasItem("AROW11",Myself) // Arrow + 2
//	HasItem("AROW12",Myself) // Arrow Of Biting
//	HasItem("AROW14",Myself) // Poisoned Arrow
//	HasItem("AROW15",Myself) // Arrow Of Ice
//	HasItem("AROW16",Myself) // Arrow Of Ice
//	HasItem("ANGAROW",Myself) // Arrow Of Fire + 2
//	HasItem("AROW1A",Myself) // Arrow + 2
//	HasItem("AROWKC",Myself) // Arrow Of Fire + 2
//	HasItem("ARROPHE2",Myself) // Arrow Of Fire + 2
//	HasItem("bdarow01",Myself) // Arrow Of Antimagic + 1
//	HasItem("bdarow03",Myself) // Flaming Arrow
//	HasItem("bdarow04",Myself) // Arrow + 3
//	HasItem("CUTAROW1",Myself) // Arrow Of Ice
//	HasItem("IAROW01",Myself) // Arrow
//	HasItem("QUIV01",Myself) // Arrow

//////////////////////////////////////////////////////// Share Ammo

IF
	!HasItem("AROW01",Myself) // Arrow
	!HasItem("AROW02",Myself) // Arrow + 1
	!HasItem("AROW03",Myself) // Arrow Of Slaying
	!HasItem("AROW04",Myself) // Acid Arrow + 1
	!HasItem("AROW05",Myself) // Arrow Of Biting
	!HasItem("AROW06",Myself) // Arrow Of Detonation
	!HasItem("AROW07",Myself) // Arrow Of Dispelling
	!HasItem("AROW08",Myself) // Arrow Of Fire + 2
	!HasItem("AROW09",Myself) // Arrow Of Ice
	!HasItem("AROW10",Myself) // Arrow Of Piercing + 1
	!HasItem("AROW11",Myself) // Arrow + 2
	!HasItem("AROW12",Myself) // Arrow Of Biting
	!HasItem("AROW14",Myself) // Poisoned Arrow
	!HasItem("AROW15",Myself) // Arrow Of Ice
	!HasItem("AROW16",Myself) // Arrow Of Ice
	!HasItem("ANGAROW",Myself) // Arrow Of Fire + 2
	!HasItem("AROW1A",Myself) // Arrow + 2
	!HasItem("AROWKC",Myself) // Arrow Of Fire + 2
	!HasItem("ARROPHE2",Myself) // Arrow Of Fire + 2
//	!HasItem("bdarow01",Myself) // Arrow Of Antimagic + 1
//	!HasItem("bdarow03",Myself) // Flaming Arrow
//	!HasItem("bdarow04",Myself) // Arrow + 3
//	!HasItem("CUTAROW1",Myself) // Arrow Of Ice
	!HasItem("IAROW01",Myself) // Arrow
	!HasItem("QUIV01",Myself) // Arrow
	HasItemCategory(Myself,BOW,FALSE)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71465) // Help: Need Arrows
        Shout(NEED_ARROWS) // Shout for help
		Continue()
END

IF
    Heard([ANYONE],NEED_ARROWS) // If someone shouted for help
    !HasItem("AROW01",LastHeardBy(Myself))
	HasItem("AROW01",Myself)
THEN
    RESPONSE #100
		//DisplayStringHead(Myself,71466) // Giving Arrows
        GiveItem("AROW01",LastHeardBy(Myself))
		Continue()
END

/////////////////////////////////////////////////////////// Change Ranged Ammo If Not Effective

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO0,0)
		Continue()
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO1,0)
		Continue()
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO2,0)
		Continue()
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	//!WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71441) // Changing Weapon
		SelectWeaponAbility(SLOT_AMMO3,0)
		Continue()
END

/////////////////////////////////////////////////////////// Use Melfs Minute Meteors If Equipped

IF
	ActionListEmpty()
	HasItem("MELFMET",Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!InParty(LastSeenBy(Myself))

	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)

	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
	!InParty(LastSeenBy(Myself))
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71446) // Melfs Minute Meteors
		AttackOneRound(LastSeenBy(Myself))
END

///////////////////////////////////////////////////////// Melee/Ranged Non-Spell Attack
// Attack enemies that have been targeted
IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	HPPercentGT(LastSeenBy(Myself),0)
	!InParty(LastSeenBy(Myself))
	//!Specifics(LastSeenBy(Myself),ALLIES)
THEN
	RESPONSE #100
		////DisplayStringHead(Myself,71497) // Normal Attack On Chosen Target
		SetGlobal("usingNormalAttack","LOCALS",1)
		AttackOneRound(LastSeenBy(Myself))
END

// If cant see nearby enemy go and attack the nearest
IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(NearestEnemyOf(Myself),0)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		////DisplayStringHead(Myself,71498) // Normal Attack On Nearby Enemies
		SetGlobal("usingNormalAttack","LOCALS",1)
		AttackOneRound(NearestEnemyOf(Myself))
END

// If no nearby enemies, attack attackers of allies
IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(LastAttackerOf(PartySlot1),0)
	!InParty(LastAttackerOf(PartySlot1))
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(PartySlot1))
		SetGlobal("usingNormalAttack","LOCALS",1)
		//DisplayStringHead(Myself,71424) // Helping Allies
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(LastAttackerOf(PartySlot2),0)
	!InParty(LastAttackerOf(PartySlot2))
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(PartySlot2))
		SetGlobal("usingNormalAttack","LOCALS",1)
		//DisplayStringHead(Myself,71424) // Helping Allies
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(LastAttackerOf(PartySlot3),0)
	!InParty(LastAttackerOf(PartySlot3))
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(PartySlot3))
		SetGlobal("usingNormalAttack","LOCALS",1)
		//DisplayStringHead(Myself,71424) // Helping Allies
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(LastAttackerOf(PartySlot4),0)
	!InParty(LastAttackerOf(PartySlot4))
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(PartySlot4))
		SetGlobal("usingNormalAttack","LOCALS",1)
		//DisplayStringHead(Myself,71424) // Helping Allies
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(LastAttackerOf(PartySlot5),0)
	!InParty(LastAttackerOf(PartySlot5))
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(PartySlot5))
		SetGlobal("usingNormalAttack","LOCALS",1)
		//DisplayStringHead(Myself,71424) // Helping Allies
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	HPPercentGT(LastAttackerOf(PartySlot6),0)
	!InParty(LastAttackerOf(PartySlot6))
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(PartySlot6))
		SetGlobal("usingNormalAttack","LOCALS",1)
		//DisplayStringHead(Myself,71424) // Helping Allies
END

////////////////////////////////////////////////////////// Wizard Use Healing If No Enemies

//IF
//	ActionListEmpty()
//    !GlobalTimerNotExpired("castnattack","LOCALS")
//	HaveSpell(INNATE_CURE_LIGHT_WOUNDS)
//	HPPercentLT(MostDamagedOf(Myself),80)
//	Class(Myself,MAGE_ALL)
//THEN
//	RESPONSE #100
//      SetGlobalTimer("castnattack","LOCALS",6)
//		//DisplayStringHead(Myself,71375) // Spell: Cure Light Wounds
//		Spell(MostDamagedOf(Myself),INNATE_CURE_LIGHT_WOUNDS)
//END

////////////////////////////////////////////////////////// Regroup if far away from each other
IF
	ActionListEmpty()
	NumInPartyGT(1)
	!Range(PartySlot2,80)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71428) // Regrouping
		MoveToObjectFollow(PartySlot2)
END

/////////////////////////////////////////////////////////// Find traps
IF
	ActionListEmpty()
	Class(Myself,THIEF_ALL)
	!ModalState(DETECTTRAPS)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself,71429) // Finding Traps
		FindTraps()
END

////////////////////////////////////////////////////////// Randomly turn around, makes them look more alive
//IF
//	ActionListEmpty()
//THEN
//	RESPONSE #100
//		//DisplayStringHead(Myself,1539)
//		RandomTurn()
//		ClearAllActions()
//END

//IF
//
//THEN
//	RESPONSE #25
//		MoveToOffset([1.1])
//	RESPONSE #25
//		MoveToOffset([1.-1])
//	RESPONSE #25
//		MoveToOffset([-1.1])
//	RESPONSE #25
//		MoveToOffset([-1.-1])
//END